<?php

use Illuminate\Database\Seeder;

class FeaturesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $features = array(
            array('id' => '1','type_id' => '1','category_id' => NULL,'feature' => 'ABS'),
            array('id' => '2','type_id' => '1','category_id' => NULL,'feature' => 'Adjustable steering wheel'),
            array('id' => '3','type_id' => '1','category_id' => NULL,'feature' => 'Air Conditioning'),
            array('id' => '4','type_id' => '1','category_id' => NULL,'feature' => 'Air Suspension'),
            array('id' => '5','type_id' => '1','category_id' => NULL,'feature' => 'Air bags'),
            array('id' => '6','type_id' => '1','category_id' => NULL,'feature' => 'Air brakes'),
            array('id' => '7','type_id' => '1','category_id' => NULL,'feature' => 'Alloy Wheels'),
            array('id' => '8','type_id' => '1','category_id' => NULL,'feature' => 'Arm rests'),
            array('id' => '9','type_id' => '1','category_id' => NULL,'feature' => 'Bulkhead (full)'),
            array('id' => '10','type_id' => '1','category_id' => NULL,'feature' => 'CD Player'),
            array('id' => '11','type_id' => '1','category_id' => NULL,'feature' => 'Cabin suspension - air'),
            array('id' => '12','type_id' => '1','category_id' => NULL,'feature' => 'Cabin suspension - mechanical'),
            array('id' => '13','type_id' => '1','category_id' => NULL,'feature' => 'Central locking'),
            array('id' => '14','type_id' => '1','category_id' => NULL,'feature' => 'Crane'),
            array('id' => '15','type_id' => '1','category_id' => NULL,'feature' => 'Cruise control'),
            array('id' => '16','type_id' => '1','category_id' => NULL,'feature' => 'Immobiliser'),
            array('id' => '17','type_id' => '1','category_id' => NULL,'feature' => 'Long range fuel tanks'),
            array('id' => '18','type_id' => '1','category_id' => NULL,'feature' => 'Onboard computer'),
            array('id' => '19','type_id' => '1','category_id' => NULL,'feature' => 'One owner'),
            array('id' => '20','type_id' => '1','category_id' => NULL,'feature' => 'PTO'),
            array('id' => '21','type_id' => '1','category_id' => NULL,'feature' => 'Power steering'),
            array('id' => '22','type_id' => '1','category_id' => NULL,'feature' => 'Differential lock'),
            array('id' => '23','type_id' => '1','category_id' => NULL,'feature' => 'Disc brakes'),
            array('id' => '24','type_id' => '1','category_id' => NULL,'feature' => 'Door - Barn door'),
            array('id' => '25','type_id' => '1','category_id' => NULL,'feature' => 'Door - Roller shutter door'),
            array('id' => '26','type_id' => '1','category_id' => NULL,'feature' => 'Doors - Triple'),
            array('id' => '27','type_id' => '1','category_id' => NULL,'feature' => 'Double bunk'),
            array('id' => '28','type_id' => '1','category_id' => NULL,'feature' => 'Drum brakes'),
            array('id' => '29','type_id' => '1','category_id' => NULL,'feature' => 'Dual passenger seat'),
            array('id' => '30','type_id' => '1','category_id' => NULL,'feature' => 'Electric Standby'),
            array('id' => '31','type_id' => '1','category_id' => NULL,'feature' => 'Electric mirrors'),
            array('id' => '32','type_id' => '1','category_id' => NULL,'feature' => 'Electric windows'),
            array('id' => '33','type_id' => '1','category_id' => NULL,'feature' => 'Electrical outlets'),
            array('id' => '34','type_id' => '1','category_id' => NULL,'feature' => 'Electronic braking system (EBS)'),
            array('id' => '35','type_id' => '1','category_id' => NULL,'feature' => 'Exhaust brake'),
            array('id' => '36','type_id' => '1','category_id' => NULL,'feature' => 'FSH'),
            array('id' => '37','type_id' => '1','category_id' => NULL,'feature' => 'Fifth wheel - fixed'),
            array('id' => '38','type_id' => '1','category_id' => NULL,'feature' => 'Fifth wheel adjustable'),
            array('id' => '39','type_id' => '1','category_id' => NULL,'feature' => 'Fog lights'),
            array('id' => '40','type_id' => '1','category_id' => NULL,'feature' => 'Heated mirrors'),
            array('id' => '41','type_id' => '1','category_id' => NULL,'feature' => 'Heated seats'),
            array('id' => '42','type_id' => '1','category_id' => NULL,'feature' => 'High roof'),
            array('id' => '43','type_id' => '1','category_id' => NULL,'feature' => 'Radio'),
            array('id' => '44','type_id' => '1','category_id' => NULL,'feature' => 'Range changer'),
            array('id' => '45','type_id' => '1','category_id' => NULL,'feature' => 'Roof hatch'),
            array('id' => '46','type_id' => '1','category_id' => NULL,'feature' => 'Rope hooks'),
            array('id' => '47','type_id' => '1','category_id' => NULL,'feature' => 'Seat belts'),
            array('id' => '48','type_id' => '1','category_id' => NULL,'feature' => 'Side wind deflectors'),
            array('id' => '49','type_id' => '1','category_id' => NULL,'feature' => 'Single bunk'),
            array('id' => '50','type_id' => '1','category_id' => NULL,'feature' => 'Spare keys'),
            array('id' => '51','type_id' => '1','category_id' => NULL,'feature' => 'Speaker system'),
            array('id' => '52','type_id' => '1','category_id' => NULL,'feature' => 'Sun Visor'),
            array('id' => '53','type_id' => '1','category_id' => NULL,'feature' => 'Sunroof'),
            array('id' => '54','type_id' => '1','category_id' => NULL,'feature' => 'Suspension - Leaf'),
            array('id' => '55','type_id' => '1','category_id' => NULL,'feature' => 'Tachograph - Analogue'),
            array('id' => '56','type_id' => '1','category_id' => NULL,'feature' => 'Tachograph - Digital'),
            array('id' => '57','type_id' => '1','category_id' => NULL,'feature' => 'Tail Lift - Column'),
            array('id' => '58','type_id' => '1','category_id' => NULL,'feature' => 'Tail Lift - Tuckaway'),
            array('id' => '59','type_id' => '1','category_id' => NULL,'feature' => 'Tail lift'),
            array('id' => '60','type_id' => '1','category_id' => NULL,'feature' => 'Tinted windows'),
            array('id' => '61','type_id' => '1','category_id' => NULL,'feature' => 'Toolbox'),
            array('id' => '62','type_id' => '1','category_id' => NULL,'feature' => 'Towbar'),
            array('id' => '63','type_id' => '1','category_id' => NULL,'feature' => 'Traction control (ASR)'),
            array('id' => '64','type_id' => '1','category_id' => NULL,'feature' => 'Wind deflector'),
            array('id' => '65','type_id' => '2','category_id' => NULL,'feature' => '1 Bucket'),
            array('id' => '66','type_id' => '2','category_id' => NULL,'feature' => '1 Year Battery Onsite Warranty'),
            array('id' => '67','type_id' => '2','category_id' => NULL,'feature' => '1/2 Tonne'),
            array('id' => '68','type_id' => '2','category_id' => NULL,'feature' => '12 Months Loler Supplied'),
            array('id' => '69','type_id' => '2','category_id' => NULL,'feature' => '1St Fill Of Oil And Coolant Included'),
            array('id' => '70','type_id' => '2','category_id' => NULL,'feature' => '2 Buckets'),
            array('id' => '71','type_id' => '2','category_id' => NULL,'feature' => '2 Cylinder Engine'),
            array('id' => '72','type_id' => '2','category_id' => NULL,'feature' => '2 Stage Full Free Lift '),
            array('id' => '73','type_id' => '2','category_id' => NULL,'feature' => '2 Stage Mast'),
            array('id' => '74','type_id' => '2','category_id' => NULL,'feature' => '2 Stage Mast '),
            array('id' => '75','type_id' => '2','category_id' => NULL,'feature' => '2015 New Build'),
            array('id' => '76','type_id' => '2','category_id' => NULL,'feature' => '3 Buckets'),
            array('id' => '77','type_id' => '2','category_id' => NULL,'feature' => '3 Cylinder Diesel Engine'),
            array('id' => '78','type_id' => '2','category_id' => NULL,'feature' => '3 Months Onsite Warranty'),
            array('id' => '79','type_id' => '2','category_id' => NULL,'feature' => '3 Months Warranty'),
            array('id' => '80','type_id' => '2','category_id' => NULL,'feature' => '3 Pole Mcb Or Mccb'),
            array('id' => '81','type_id' => '2','category_id' => NULL,'feature' => '3 Stage Full Free Lift'),
            array('id' => '82','type_id' => '2','category_id' => NULL,'feature' => '3 Wheel Model'),
            array('id' => '83','type_id' => '2','category_id' => NULL,'feature' => '3 Wheel Model '),
            array('id' => '84','type_id' => '2','category_id' => NULL,'feature' => '30 Days Warranty'),
            array('id' => '85','type_id' => '2','category_id' => NULL,'feature' => '3Rd And 4Th Hydraulics'),
            array('id' => '86','type_id' => '2','category_id' => NULL,'feature' => '3Rd Hydraulic Lever'),
            array('id' => '87','type_id' => '2','category_id' => NULL,'feature' => '3Rd Hydraulic Lever Fitted'),
            array('id' => '88','type_id' => '2','category_id' => NULL,'feature' => '4 Cylinder Diesel Engine'),
            array('id' => '89','type_id' => '2','category_id' => NULL,'feature' => '4 Stage Full Free Lift (Quad Mast)'),
            array('id' => '90','type_id' => '2','category_id' => NULL,'feature' => '4Wd'),
            array('id' => '91','type_id' => '2','category_id' => NULL,'feature' => '6 Months Onsite Warranty'),
            array('id' => '92','type_id' => '2','category_id' => NULL,'feature' => '6 Months Warranty '),
            array('id' => '93','type_id' => '2','category_id' => NULL,'feature' => '8Hr Bunded Base Tank'),
            array('id' => '94','type_id' => '2','category_id' => NULL,'feature' => 'Adjustable Steering Wheel'),
            array('id' => '95','type_id' => '2','category_id' => NULL,'feature' => 'Adjustable Track Widths'),
            array('id' => '96','type_id' => '2','category_id' => NULL,'feature' => 'Air  Fuel And Oil Filters'),
            array('id' => '97','type_id' => '2','category_id' => NULL,'feature' => 'Air Conditioning'),
            array('id' => '98','type_id' => '2','category_id' => NULL,'feature' => 'All European Rustproof Canopy'),
            array('id' => '99','type_id' => '2','category_id' => NULL,'feature' => 'Anti Theft System'),
            array('id' => '100','type_id' => '2','category_id' => NULL,'feature' => 'Articulated Forklift'),
            array('id' => '101','type_id' => '2','category_id' => NULL,'feature' => 'Canopy'),
            array('id' => '102','type_id' => '2','category_id' => NULL,'feature' => 'Canopy Viewing Window'),
            array('id' => '103','type_id' => '2','category_id' => NULL,'feature' => 'Cd Player'),
            array('id' => '104','type_id' => '2','category_id' => NULL,'feature' => 'Ce Marked'),
            array('id' => '105','type_id' => '2','category_id' => NULL,'feature' => 'Container Specification'),
            array('id' => '106','type_id' => '2','category_id' => NULL,'feature' => 'Csc Plated'),
            array('id' => '107','type_id' => '2','category_id' => NULL,'feature' => 'Industrial Exhaust Silencer'),
            array('id' => '108','type_id' => '2','category_id' => NULL,'feature' => 'Joystick'),
            array('id' => '109','type_id' => '2','category_id' => NULL,'feature' => 'Key Start'),
            array('id' => '110','type_id' => '2','category_id' => NULL,'feature' => 'Kubota Evts Efficient Engine'),
            array('id' => '111','type_id' => '2','category_id' => NULL,'feature' => 'Lock Box Fitted'),
            array('id' => '112','type_id' => '2','category_id' => NULL,'feature' => 'Lockable Lid'),
            array('id' => '113','type_id' => '2','category_id' => NULL,'feature' => 'Low Hours'),
            array('id' => '114','type_id' => '2','category_id' => NULL,'feature' => 'Low Oil Pressure Protection'),
            array('id' => '115','type_id' => '2','category_id' => NULL,'feature' => 'Mains Battery Charger'),
            array('id' => '116','type_id' => '2','category_id' => NULL,'feature' => 'Manufacturers Warranty'),
            array('id' => '117','type_id' => '2','category_id' => NULL,'feature' => 'No Sideshift'),
            array('id' => '118','type_id' => '2','category_id' => NULL,'feature' => 'Non Marking Tyres'),
            array('id' => '119','type_id' => '2','category_id' => NULL,'feature' => 'Optional Ats Panel'),
            array('id' => '120','type_id' => '2','category_id' => NULL,'feature' => 'Optional Battery Charger'),
            array('id' => '121','type_id' => '2','category_id' => NULL,'feature' => 'Optional Low Coolant Level Protection'),
            array('id' => '122','type_id' => '2','category_id' => NULL,'feature' => 'Optional Mains Coolant Heater'),
            array('id' => '123','type_id' => '2','category_id' => NULL,'feature' => 'Optional Mains Oil Heater'),
            array('id' => '124','type_id' => '2','category_id' => NULL,'feature' => 'Optional Network/Gsm Module'),
            array('id' => '125','type_id' => '2','category_id' => NULL,'feature' => 'Outstanding Original Condition'),
            array('id' => '126','type_id' => '2','category_id' => NULL,'feature' => 'Overspeed Protection'),
            array('id' => '127','type_id' => '2','category_id' => NULL,'feature' => 'Perkins Diesel Generator'),
            array('id' => '128','type_id' => '2','category_id' => NULL,'feature' => 'Piped For Attachments'),
            array('id' => '129','type_id' => '2','category_id' => NULL,'feature' => 'Piped For Breaker'),
            array('id' => '130','type_id' => '2','category_id' => NULL,'feature' => 'Piped To Carriage'),
            array('id' => '131','type_id' => '2','category_id' => NULL,'feature' => 'Pneumatic Tyres'),
            array('id' => '132','type_id' => '2','category_id' => NULL,'feature' => 'Pyroban Zone 2 '),
            array('id' => '133','type_id' => '2','category_id' => NULL,'feature' => 'Q Hitch'),
            array('id' => '134','type_id' => '2','category_id' => NULL,'feature' => 'Quick Hitch'),
            array('id' => '135','type_id' => '2','category_id' => NULL,'feature' => 'Dead Man Key'),
            array('id' => '136','type_id' => '2','category_id' => NULL,'feature' => 'Expanding Tracks'),
            array('id' => '137','type_id' => '2','category_id' => NULL,'feature' => 'Expanding Undercarriage '),
            array('id' => '138','type_id' => '2','category_id' => NULL,'feature' => 'External Emergency Stop'),
            array('id' => '139','type_id' => '2','category_id' => NULL,'feature' => 'Fan  Matrix Guard'),
            array('id' => '140','type_id' => '2','category_id' => NULL,'feature' => 'Fuel Contents Gauge'),
            array('id' => '141','type_id' => '2','category_id' => NULL,'feature' => 'Full Cab'),
            array('id' => '142','type_id' => '2','category_id' => NULL,'feature' => 'Full Cab '),
            array('id' => '143','type_id' => '2','category_id' => NULL,'feature' => 'Full Steel Cab'),
            array('id' => '144','type_id' => '2','category_id' => NULL,'feature' => 'Heavy Duty Fuel Lines'),
            array('id' => '145','type_id' => '2','category_id' => NULL,'feature' => 'Heavy Duty Lead Acid Battery'),
            array('id' => '146','type_id' => '2','category_id' => NULL,'feature' => 'High Cube'),
            array('id' => '147','type_id' => '2','category_id' => NULL,'feature' => 'High Engine Temp Protection'),
            array('id' => '148','type_id' => '2','category_id' => NULL,'feature' => 'High Speed'),
            array('id' => '149','type_id' => '2','category_id' => NULL,'feature' => 'High Tip'),
            array('id' => '150','type_id' => '2','category_id' => NULL,'feature' => 'Hydraulic Shift'),
            array('id' => '151','type_id' => '2','category_id' => NULL,'feature' => 'Hydrostatic'),
            array('id' => '152','type_id' => '2','category_id' => NULL,'feature' => 'Hydrostatic Drive'),
            array('id' => '153','type_id' => '2','category_id' => NULL,'feature' => 'Radio'),
            array('id' => '154','type_id' => '2','category_id' => NULL,'feature' => 'Rear Camera'),
            array('id' => '155','type_id' => '2','category_id' => NULL,'feature' => 'Remote Control'),
            array('id' => '156','type_id' => '2','category_id' => NULL,'feature' => 'Residential Exhaust Silencer'),
            array('id' => '157','type_id' => '2','category_id' => NULL,'feature' => 'Reverse Alarm'),
            array('id' => '158','type_id' => '2','category_id' => NULL,'feature' => 'Reverse Camera'),
            array('id' => '159','type_id' => '2','category_id' => NULL,'feature' => 'Road Registered'),
            array('id' => '160','type_id' => '2','category_id' => NULL,'feature' => 'Roadliner Pads'),
            array('id' => '161','type_id' => '2','category_id' => NULL,'feature' => 'Rustproof Canopy '),
            array('id' => '162','type_id' => '2','category_id' => NULL,'feature' => 'Seat Belts'),
            array('id' => '163','type_id' => '2','category_id' => NULL,'feature' => 'Security System'),
            array('id' => '164','type_id' => '2','category_id' => NULL,'feature' => 'Sideshifting Fork Positioner '),
            array('id' => '165','type_id' => '2','category_id' => NULL,'feature' => 'Solid Flooring'),
            array('id' => '166','type_id' => '2','category_id' => NULL,'feature' => 'Spotlights'),
            array('id' => '167','type_id' => '2','category_id' => NULL,'feature' => 'Stand On Dumper'),
            array('id' => '168','type_id' => '2','category_id' => NULL,'feature' => 'Standard Iso8528 Works Test'),
            array('id' => '169','type_id' => '2','category_id' => NULL,'feature' => 'Standard Safety Features'),
            array('id' => '170','type_id' => '2','category_id' => NULL,'feature' => 'Straight Tip'),
            array('id' => '171','type_id' => '2','category_id' => NULL,'feature' => 'Swivel Tip'),
            array('id' => '172','type_id' => '2','category_id' => NULL,'feature' => 'Toolbox'),
            array('id' => '173','type_id' => '2','category_id' => NULL,'feature' => 'Top Specification Dse Controller'),
            array('id' => '174','type_id' => '2','category_id' => NULL,'feature' => 'Tropical Radiator'),
            array('id' => '175','type_id' => '2','category_id' => NULL,'feature' => 'Two Speed Travel'),
            array('id' => '176','type_id' => '2','category_id' => NULL,'feature' => 'User Manual(S)'),
            array('id' => '177','type_id' => '2','category_id' => NULL,'feature' => 'Waist High Locking Handles'),
            array('id' => '178','type_id' => '2','category_id' => NULL,'feature' => 'Warranty'),
            array('id' => '179','type_id' => '2','category_id' => NULL,'feature' => 'Weather Cab Fitted'),
            array('id' => '180','type_id' => '2','category_id' => NULL,'feature' => 'Wind And Watertight'),
            array('id' => '181','type_id' => '2','category_id' => NULL,'feature' => 'Yanmar Diesel Engine '),
            array('id' => '182','type_id' => '2','category_id' => NULL,'feature' => 'Zero Tail Swing'),
            array('id' => '183','type_id' => '3','category_id' => NULL,'feature' => '3 Point Linkage'),
            array('id' => '184','type_id' => '3','category_id' => NULL,'feature' => '3 Point Linkage Mounted'),
            array('id' => '185','type_id' => '3','category_id' => NULL,'feature' => '4X4'),
            array('id' => '186','type_id' => '3','category_id' => NULL,'feature' => 'Abs'),
            array('id' => '187','type_id' => '3','category_id' => NULL,'feature' => 'Adjustable Steering Wheel'),
            array('id' => '188','type_id' => '3','category_id' => NULL,'feature' => 'Air And Oil Brakes'),
            array('id' => '189','type_id' => '3','category_id' => NULL,'feature' => 'Air Brakes'),
            array('id' => '190','type_id' => '3','category_id' => NULL,'feature' => 'Air Conditioning'),
            array('id' => '191','type_id' => '3','category_id' => NULL,'feature' => 'Air Suspension'),
            array('id' => '192','type_id' => '3','category_id' => NULL,'feature' => 'Anti Theft System'),
            array('id' => '193','type_id' => '3','category_id' => NULL,'feature' => 'Arm Rests'),
            array('id' => '194','type_id' => '3','category_id' => NULL,'feature' => 'Cabin Suspension - Air'),
            array('id' => '195','type_id' => '3','category_id' => NULL,'feature' => 'Cabin Suspension - Mechanical'),
            array('id' => '196','type_id' => '3','category_id' => NULL,'feature' => 'Cd Player'),
            array('id' => '197','type_id' => '3','category_id' => NULL,'feature' => 'Clutchless Forward-Reverse Shuttle'),
            array('id' => '198','type_id' => '3','category_id' => NULL,'feature' => 'Cruise Control'),
            array('id' => '199','type_id' => '3','category_id' => NULL,'feature' => 'Manufacturers Warranty'),
            array('id' => '200','type_id' => '3','category_id' => NULL,'feature' => 'Onboard Computer'),
            array('id' => '201','type_id' => '3','category_id' => NULL,'feature' => 'Power Slew'),
            array('id' => '202','type_id' => '3','category_id' => NULL,'feature' => 'Pto'),
            array('id' => '203','type_id' => '3','category_id' => NULL,'feature' => 'Electrical Outlets'),
            array('id' => '204','type_id' => '3','category_id' => NULL,'feature' => 'Fire Extinguisher'),
            array('id' => '205','type_id' => '3','category_id' => NULL,'feature' => 'High Speed'),
            array('id' => '206','type_id' => '3','category_id' => NULL,'feature' => 'Hydraulic Breakout'),
            array('id' => '207','type_id' => '3','category_id' => NULL,'feature' => 'Hydraulic Shift'),
            array('id' => '208','type_id' => '3','category_id' => NULL,'feature' => 'Radio'),
            array('id' => '209','type_id' => '3','category_id' => NULL,'feature' => 'Rotor Reverse '),
            array('id' => '210','type_id' => '3','category_id' => NULL,'feature' => 'Seat Belts'),
            array('id' => '211','type_id' => '3','category_id' => NULL,'feature' => 'Spotlights'),
            array('id' => '212','type_id' => '3','category_id' => NULL,'feature' => 'Spring Supension'),
            array('id' => '213','type_id' => '3','category_id' => NULL,'feature' => 'Sprung Drawbar'),
            array('id' => '214','type_id' => '3','category_id' => NULL,'feature' => 'Sprung Ramps'),
            array('id' => '215','type_id' => '3','category_id' => NULL,'feature' => 'Towbar'),
            array('id' => '216','type_id' => '3','category_id' => NULL,'feature' => 'Warranty'),
            array('id' => '217','type_id' => '4','category_id' => NULL,'feature' => '16" light alloy wheels'),
            array('id' => '218','type_id' => '4','category_id' => NULL,'feature' => '17" light alloy wheels'),
            array('id' => '219','type_id' => '4','category_id' => NULL,'feature' => '18" light alloy wheels'),
            array('id' => '220','type_id' => '4','category_id' => NULL,'feature' => '19" light alloy wheels'),
            array('id' => '221','type_id' => '4','category_id' => NULL,'feature' => '3x3 point rear seat belts'),
            array('id' => '222','type_id' => '4','category_id' => NULL,'feature' => 'ABS'),
            array('id' => '223','type_id' => '4','category_id' => NULL,'feature' => 'Adjustable seats'),
            array('id' => '224','type_id' => '4','category_id' => NULL,'feature' => 'Adjustable steering column/wheel'),
            array('id' => '225','type_id' => '4','category_id' => NULL,'feature' => 'Air conditioning'),
            array('id' => '226','type_id' => '4','category_id' => NULL,'feature' => 'Alarm'),
            array('id' => '227','type_id' => '4','category_id' => NULL,'feature' => 'Alarm remote controlled'),
            array('id' => '228','type_id' => '4','category_id' => NULL,'feature' => 'Alloy wheels'),
            array('id' => '229','type_id' => '4','category_id' => NULL,'feature' => 'Anti theft system'),
            array('id' => '230','type_id' => '4','category_id' => NULL,'feature' => 'Bluetooth'),
            array('id' => '231','type_id' => '4','category_id' => NULL,'feature' => 'Body coloured bumpers'),
            array('id' => '232','type_id' => '4','category_id' => NULL,'feature' => 'Body kit'),
            array('id' => '233','type_id' => '4','category_id' => NULL,'feature' => 'CD'),
            array('id' => '234','type_id' => '4','category_id' => NULL,'feature' => 'CD Multichanger'),
            array('id' => '235','type_id' => '4','category_id' => NULL,'feature' => 'Central locking'),
            array('id' => '236','type_id' => '4','category_id' => NULL,'feature' => 'Child locks'),
            array('id' => '237','type_id' => '4','category_id' => NULL,'feature' => 'Climate Control'),
            array('id' => '238','type_id' => '4','category_id' => NULL,'feature' => 'Cloth upholstery'),
            array('id' => '239','type_id' => '4','category_id' => NULL,'feature' => 'Computer'),
            array('id' => '240','type_id' => '4','category_id' => NULL,'feature' => 'Cruise control'),
            array('id' => '241','type_id' => '4','category_id' => NULL,'feature' => 'Immobiliser'),
            array('id' => '242','type_id' => '4','category_id' => NULL,'feature' => 'Isofix child seat anchor points'),
            array('id' => '243','type_id' => '4','category_id' => NULL,'feature' => 'Leather seats'),
            array('id' => '244','type_id' => '4','category_id' => NULL,'feature' => 'Leather upholstery'),
            array('id' => '245','type_id' => '4','category_id' => NULL,'feature' => 'Locking wheel nuts'),
            array('id' => '246','type_id' => '4','category_id' => NULL,'feature' => 'Manufacturers warranty'),
            array('id' => '247','type_id' => '4','category_id' => NULL,'feature' => 'Metallic paintwork'),
            array('id' => '248','type_id' => '4','category_id' => NULL,'feature' => 'Mirrors electric'),
            array('id' => '249','type_id' => '4','category_id' => NULL,'feature' => 'Mirrors electric and heated'),
            array('id' => '250','type_id' => '4','category_id' => NULL,'feature' => 'Multi function steering wheel'),
            array('id' => '251','type_id' => '4','category_id' => NULL,'feature' => 'Navigation system'),
            array('id' => '252','type_id' => '4','category_id' => NULL,'feature' => 'Outside temperature meter'),
            array('id' => '253','type_id' => '4','category_id' => NULL,'feature' => 'PAS'),
            array('id' => '254','type_id' => '4','category_id' => NULL,'feature' => 'Parking sensor'),
            array('id' => '255','type_id' => '4','category_id' => NULL,'feature' => 'Passenger airbag'),
            array('id' => '256','type_id' => '4','category_id' => NULL,'feature' => 'Power Steering'),
            array('id' => '257','type_id' => '4','category_id' => NULL,'feature' => 'Driver airbag'),
            array('id' => '258','type_id' => '4','category_id' => NULL,'feature' => 'Drivers airbag'),
            array('id' => '259','type_id' => '4','category_id' => NULL,'feature' => 'Electric mirrors'),
            array('id' => '260','type_id' => '4','category_id' => NULL,'feature' => 'Electric roof'),
            array('id' => '261','type_id' => '4','category_id' => NULL,'feature' => 'Electric sunroof'),
            array('id' => '262','type_id' => '4','category_id' => NULL,'feature' => 'Electric windows'),
            array('id' => '263','type_id' => '4','category_id' => NULL,'feature' => 'Electrically adjustable seats'),
            array('id' => '264','type_id' => '4','category_id' => NULL,'feature' => 'Foglights'),
            array('id' => '265','type_id' => '4','category_id' => NULL,'feature' => 'Folding rear seats'),
            array('id' => '266','type_id' => '4','category_id' => NULL,'feature' => 'Front armrest'),
            array('id' => '267','type_id' => '4','category_id' => NULL,'feature' => 'Front electric windows'),
            array('id' => '268','type_id' => '4','category_id' => NULL,'feature' => 'Front head restraints'),
            array('id' => '269','type_id' => '4','category_id' => NULL,'feature' => 'Full Dealer Facilities'),
            array('id' => '270','type_id' => '4','category_id' => NULL,'feature' => 'Full service history'),
            array('id' => '271','type_id' => '4','category_id' => NULL,'feature' => 'GPS'),
            array('id' => '272','type_id' => '4','category_id' => NULL,'feature' => 'Head restraints'),
            array('id' => '273','type_id' => '4','category_id' => NULL,'feature' => 'Headlight washers'),
            array('id' => '274','type_id' => '4','category_id' => NULL,'feature' => 'Heated screen'),
            array('id' => '275','type_id' => '4','category_id' => NULL,'feature' => 'Heated seats'),
            array('id' => '276','type_id' => '4','category_id' => NULL,'feature' => 'Height adjustable drivers seat'),
            array('id' => '277','type_id' => '4','category_id' => NULL,'feature' => 'Radio'),
            array('id' => '278','type_id' => '4','category_id' => NULL,'feature' => 'Radio/CD'),
            array('id' => '279','type_id' => '4','category_id' => NULL,'feature' => 'Radio/CD/MP3'),
            array('id' => '280','type_id' => '4','category_id' => NULL,'feature' => 'Rain sensor'),
            array('id' => '281','type_id' => '4','category_id' => NULL,'feature' => 'Rear headrests'),
            array('id' => '282','type_id' => '4','category_id' => NULL,'feature' => 'Rear wiper'),
            array('id' => '283','type_id' => '4','category_id' => NULL,'feature' => 'Remote central locking'),
            array('id' => '284','type_id' => '4','category_id' => NULL,'feature' => 'Remote locking'),
            array('id' => '285','type_id' => '4','category_id' => NULL,'feature' => 'Roof rails'),
            array('id' => '286','type_id' => '4','category_id' => NULL,'feature' => 'Sat Nav'),
            array('id' => '287','type_id' => '4','category_id' => NULL,'feature' => 'Satelite Navigation'),
            array('id' => '288','type_id' => '4','category_id' => NULL,'feature' => 'Tinted glass'),
            array('id' => '289','type_id' => '4','category_id' => NULL,'feature' => 'Towbar'),
            array('id' => '290','type_id' => '4','category_id' => NULL,'feature' => 'Traction control'),
            array('id' => '291','type_id' => '4','category_id' => NULL,'feature' => 'Trip computer'),
            array('id' => '292','type_id' => '4','category_id' => NULL,'feature' => 'Windows front + rear electric'),
            array('id' => '293','type_id' => '4','category_id' => NULL,'feature' => 'Xenon lights'),
            array('id' => '294','type_id' => '5','category_id' => NULL,'feature' => '65 Plate'),
            array('id' => '295','type_id' => '5','category_id' => NULL,'feature' => 'ABS'),
            array('id' => '296','type_id' => '5','category_id' => NULL,'feature' => 'ABS And ASR'),
            array('id' => '297','type_id' => '5','category_id' => NULL,'feature' => 'ADR compliant'),
            array('id' => '298','type_id' => '5','category_id' => NULL,'feature' => 'Adjustable steering wheel'),
            array('id' => '299','type_id' => '5','category_id' => NULL,'feature' => 'Air Bag'),
            array('id' => '300','type_id' => '5','category_id' => NULL,'feature' => 'Air Conditioning'),
            array('id' => '301','type_id' => '5','category_id' => NULL,'feature' => 'Air bags'),
            array('id' => '302','type_id' => '5','category_id' => NULL,'feature' => 'Air brakes'),
            array('id' => '303','type_id' => '5','category_id' => NULL,'feature' => 'Airbag'),
            array('id' => '304','type_id' => '5','category_id' => NULL,'feature' => 'Alarm'),
            array('id' => '305','type_id' => '5','category_id' => NULL,'feature' => 'Alloy Wheels'),
            array('id' => '306','type_id' => '5','category_id' => NULL,'feature' => 'Anti theft system'),
            array('id' => '307','type_id' => '5','category_id' => NULL,'feature' => 'Arm Rest'),
            array('id' => '308','type_id' => '5','category_id' => NULL,'feature' => 'Arm rests'),
            array('id' => '309','type_id' => '5','category_id' => NULL,'feature' => 'Aux'),
            array('id' => '310','type_id' => '5','category_id' => NULL,'feature' => 'Aux Socket'),
            array('id' => '311','type_id' => '5','category_id' => NULL,'feature' => 'Auxiliary Audio Input Jack for iPod etc'),
            array('id' => '312','type_id' => '5','category_id' => NULL,'feature' => 'Bluetooth'),
            array('id' => '313','type_id' => '5','category_id' => NULL,'feature' => 'Bluetooth Handsfree Telephone Kit'),
            array('id' => '314','type_id' => '5','category_id' => NULL,'feature' => 'Bluetooth Phone Prep'),
            array('id' => '315','type_id' => '5','category_id' => NULL,'feature' => 'Bluetooth Radio/CD'),
            array('id' => '316','type_id' => '5','category_id' => NULL,'feature' => 'Bluetooth/Tel'),
            array('id' => '317','type_id' => '5','category_id' => NULL,'feature' => 'Body Coloured Bumpers and Mirrors '),
            array('id' => '318','type_id' => '5','category_id' => NULL,'feature' => 'Bulkhead (full)'),
            array('id' => '319','type_id' => '5','category_id' => NULL,'feature' => 'Bulkhead (part)'),
            array('id' => '320','type_id' => '5','category_id' => NULL,'feature' => 'CD Player'),
            array('id' => '321','type_id' => '5','category_id' => NULL,'feature' => 'Captain Seats'),
            array('id' => '322','type_id' => '5','category_id' => NULL,'feature' => 'Central locking'),
            array('id' => '323','type_id' => '5','category_id' => NULL,'feature' => 'Chrome Side Bars'),
            array('id' => '324','type_id' => '5','category_id' => NULL,'feature' => 'Crosswind Assist'),
            array('id' => '325','type_id' => '5','category_id' => NULL,'feature' => 'Cruise control'),
            array('id' => '326','type_id' => '5','category_id' => NULL,'feature' => 'Immobiliser'),
            array('id' => '327','type_id' => '5','category_id' => NULL,'feature' => 'Insulated'),
            array('id' => '328','type_id' => '5','category_id' => NULL,'feature' => 'Internal shelving'),
            array('id' => '329','type_id' => '5','category_id' => NULL,'feature' => 'Jack'),
            array('id' => '330','type_id' => '5','category_id' => NULL,'feature' => 'Leather Steering Wheel and Gear Lever'),
            array('id' => '331','type_id' => '5','category_id' => NULL,'feature' => 'Leather seats'),
            array('id' => '332','type_id' => '5','category_id' => NULL,'feature' => 'Load Liner'),
            array('id' => '333','type_id' => '5','category_id' => NULL,'feature' => 'MP3 Compatible CD Player'),
            array('id' => '334','type_id' => '5','category_id' => NULL,'feature' => 'Manufacturers warranty'),
            array('id' => '335','type_id' => '5','category_id' => NULL,'feature' => 'Metallic paintwork'),
            array('id' => '336','type_id' => '5','category_id' => NULL,'feature' => 'Multi Function Steering Wheel'),
            array('id' => '337','type_id' => '5','category_id' => NULL,'feature' => 'Multi Function Steering Wheel Controls'),
            array('id' => '338','type_id' => '5','category_id' => NULL,'feature' => 'Onboard computer'),
            array('id' => '339','type_id' => '5','category_id' => NULL,'feature' => 'Parking Sensors'),
            array('id' => '340','type_id' => '5','category_id' => NULL,'feature' => 'Ply lined'),
            array('id' => '341','type_id' => '5','category_id' => NULL,'feature' => 'Power steering'),
            array('id' => '342','type_id' => '5','category_id' => NULL,'feature' => 'Privacy Glass'),
            array('id' => '343','type_id' => '5','category_id' => NULL,'feature' => 'Quick Clear Heated Windscreen'),
            array('id' => '344','type_id' => '5','category_id' => NULL,'feature' => 'Day Time Driving Lights'),
            array('id' => '345','type_id' => '5','category_id' => NULL,'feature' => 'Differential lock'),
            array('id' => '346','type_id' => '5','category_id' => NULL,'feature' => 'Disc brakes'),
            array('id' => '347','type_id' => '5','category_id' => NULL,'feature' => 'Door - Barn door'),
            array('id' => '348','type_id' => '5','category_id' => NULL,'feature' => 'Door - LHSD'),
            array('id' => '349','type_id' => '5','category_id' => NULL,'feature' => 'Door - RHSD'),
            array('id' => '350','type_id' => '5','category_id' => NULL,'feature' => 'Door - Twin side door'),
            array('id' => '351','type_id' => '5','category_id' => NULL,'feature' => 'Door - Up and over door'),
            array('id' => '352','type_id' => '5','category_id' => NULL,'feature' => 'Door- Roller shutter door'),
            array('id' => '353','type_id' => '5','category_id' => NULL,'feature' => 'Double Rear Wheels'),
            array('id' => '354','type_id' => '5','category_id' => NULL,'feature' => 'Driver Airbag'),
            array('id' => '355','type_id' => '5','category_id' => NULL,'feature' => 'Drivers Airbag'),
            array('id' => '356','type_id' => '5','category_id' => NULL,'feature' => 'Dual passenger seat'),
            array('id' => '357','type_id' => '5','category_id' => NULL,'feature' => 'EDC'),
            array('id' => '358','type_id' => '5','category_id' => NULL,'feature' => 'Electric mirrors'),
            array('id' => '359','type_id' => '5','category_id' => NULL,'feature' => 'Electric windows'),
            array('id' => '360','type_id' => '5','category_id' => NULL,'feature' => 'Electronic Stability Control (ESC)'),
            array('id' => '361','type_id' => '5','category_id' => NULL,'feature' => 'Electronic brake assist (EBA)'),
            array('id' => '362','type_id' => '5','category_id' => NULL,'feature' => 'Electronic brake power distribution (EBV)'),
            array('id' => '363','type_id' => '5','category_id' => NULL,'feature' => 'Electronic brakeforce distribution (EBD)'),
            array('id' => '364','type_id' => '5','category_id' => NULL,'feature' => 'Electronic braking system (EBS)'),
            array('id' => '365','type_id' => '5','category_id' => NULL,'feature' => 'Extra seating'),
            array('id' => '366','type_id' => '5','category_id' => NULL,'feature' => 'FSH'),
            array('id' => '367','type_id' => '5','category_id' => NULL,'feature' => 'Fog lights'),
            array('id' => '368','type_id' => '5','category_id' => NULL,'feature' => 'Front Fog Lights '),
            array('id' => '369','type_id' => '5','category_id' => NULL,'feature' => 'Full side opening'),
            array('id' => '370','type_id' => '5','category_id' => NULL,'feature' => 'Headlights washer'),
            array('id' => '371','type_id' => '5','category_id' => NULL,'feature' => 'Heated Screen'),
            array('id' => '372','type_id' => '5','category_id' => NULL,'feature' => 'Heated mirrors'),
            array('id' => '373','type_id' => '5','category_id' => NULL,'feature' => 'Heated seats'),
            array('id' => '374','type_id' => '5','category_id' => NULL,'feature' => 'High roof'),
            array('id' => '375','type_id' => '5','category_id' => NULL,'feature' => 'Hill Start Assist'),
            array('id' => '376','type_id' => '5','category_id' => NULL,'feature' => 'Radio/USB/AUX'),
            array('id' => '377','type_id' => '5','category_id' => NULL,'feature' => 'Rear Loading Doors '),
            array('id' => '378','type_id' => '5','category_id' => NULL,'feature' => 'Rear Parking Sensors'),
            array('id' => '379','type_id' => '5','category_id' => NULL,'feature' => 'Rear parking sensors'),
            array('id' => '380','type_id' => '5','category_id' => NULL,'feature' => 'Reflective Chevron Markings on Rear'),
            array('id' => '381','type_id' => '5','category_id' => NULL,'feature' => 'Remote Central Locking'),
            array('id' => '382','type_id' => '5','category_id' => NULL,'feature' => 'Remote Control Central Locking'),
            array('id' => '383','type_id' => '5','category_id' => NULL,'feature' => 'Remote central locking'),
            array('id' => '384','type_id' => '5','category_id' => NULL,'feature' => 'Roof Rails'),
            array('id' => '385','type_id' => '5','category_id' => NULL,'feature' => 'Roof rack'),
            array('id' => '386','type_id' => '5','category_id' => NULL,'feature' => 'Roof vent'),
            array('id' => '387','type_id' => '5','category_id' => NULL,'feature' => 'Sat nav'),
            array('id' => '388','type_id' => '5','category_id' => NULL,'feature' => 'Seat belts'),
            array('id' => '389','type_id' => '5','category_id' => NULL,'feature' => 'Shelves'),
            array('id' => '390','type_id' => '5','category_id' => NULL,'feature' => 'Side Loading Door'),
            array('id' => '391','type_id' => '5','category_id' => NULL,'feature' => 'Side skirts'),
            array('id' => '392','type_id' => '5','category_id' => NULL,'feature' => 'Spare Key'),
            array('id' => '393','type_id' => '5','category_id' => NULL,'feature' => 'Spare keys'),
            array('id' => '394','type_id' => '5','category_id' => NULL,'feature' => 'Speaker system'),
            array('id' => '395','type_id' => '5','category_id' => NULL,'feature' => 'Spotlights'),
            array('id' => '396','type_id' => '5','category_id' => NULL,'feature' => 'Suspension - Leaf'),
            array('id' => '397','type_id' => '5','category_id' => NULL,'feature' => 'TWIN Sliding Side Loading Doors'),
            array('id' => '398','type_id' => '5','category_id' => NULL,'feature' => 'Tachograph - Digital'),
            array('id' => '399','type_id' => '5','category_id' => NULL,'feature' => 'Tail Lift'),
            array('id' => '400','type_id' => '5','category_id' => NULL,'feature' => 'Tailgate'),
            array('id' => '401','type_id' => '5','category_id' => NULL,'feature' => 'Tinted windows'),
            array('id' => '402','type_id' => '5','category_id' => NULL,'feature' => 'Towbar'),
            array('id' => '403','type_id' => '5','category_id' => NULL,'feature' => 'Traction control (ASR)'),
            array('id' => '404','type_id' => '5','category_id' => NULL,'feature' => 'Warranty'),
            array('id' => '405','type_id' => '5','category_id' => NULL,'feature' => 'Wind deflector')
        );

        DB::table("features")->insert($features);
    }
}
