<?php

use Illuminate\Database\Seeder;

class MakeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $makes = array(
            array('type_id' => '1','make' => 'AHP'),
            array('type_id' => '1','make' => 'ARB'),
            array('type_id' => '1','make' => 'AWD'),
            array('type_id' => '1','make' => 'ABEL'),
            array('type_id' => '1','make' => 'ADCLIFFE'),
            array('type_id' => '1','make' => 'AFRIT'),
            array('type_id' => '1','make' => 'ANDOVER'),
            array('type_id' => '1','make' => 'ANTEO'),
            array('type_id' => '1','make' => 'AVIA'),
            array('type_id' => '1','make' => 'BMC'),
            array('type_id' => '1','make' => 'BMI'),
            array('type_id' => '1','make' => 'BR TRAILER'),
            array('type_id' => '1','make' => 'BEDFORD'),
            array('type_id' => '1','make' => 'BEECHWOOD'),
            array('type_id' => '1','make' => 'BOALLOY'),
            array('type_id' => '1','make' => 'BOUGHTON'),
            array('type_id' => '1','make' => 'BROSHUIS'),
            array('type_id' => '1','make' => 'BUCKSTONE'),
            array('type_id' => '1','make' => 'BURG'),
            array('type_id' => '1','make' => 'BUSAF'),
            array('type_id' => '1','make' => 'BUTTERFIELD'),
            array('type_id' => '1','make' => 'CTS'),
            array('type_id' => '1','make' => 'CARGOLITE'),
            array('type_id' => '1','make' => 'CARRYMASTER'),
            array('type_id' => '1','make' => 'CARTWRIGHT'),
            array('type_id' => '1','make' => 'CHEREAU'),
            array('type_id' => '1','make' => 'CLAYTON'),
            array('type_id' => '1','make' => 'COBALT'),
            array('type_id' => '1','make' => 'COMETTO'),
            array('type_id' => '1','make' => 'CONSTELLATION'),
            array('type_id' => '1','make' => 'COPELYN'),
            array('type_id' => '1','make' => 'CORUS'),
            array('type_id' => '1','make' => 'CRANE FRUEHAUF'),
            array('type_id' => '1','make' => 'CRAVEN TASKER'),
            array('type_id' => '1','make' => 'DAF'),
            array('type_id' => '1','make' => 'DAEWOO'),
            array('type_id' => '1','make' => 'DELTA'),
            array('type_id' => '1','make' => 'DENNIS'),
            array('type_id' => '1','make' => 'DENNIS EAGLE'),
            array('type_id' => '1','make' => 'DENNISON'),
            array('type_id' => '1','make' => 'DON-BUR'),
            array('type_id' => '1','make' => 'DONGFENG'),
            array('type_id' => '1','make' => 'DOUGLAS'),
            array('type_id' => '1','make' => 'ERF'),
            array('type_id' => '1','make' => 'ETE'),
            array('type_id' => '1','make' => 'ENTERPRISE'),
            array('type_id' => '1','make' => 'FAW'),
            array('type_id' => '1','make' => 'FUSO'),
            array('type_id' => '1','make' => 'FARLOW'),
            array('type_id' => '1','make' => 'FAYMONVILLE'),
            array('type_id' => '1','make' => 'FELDBINDER'),
            array('type_id' => '1','make' => 'FODEN'),
            array('type_id' => '1','make' => 'FORD'),
            array('type_id' => '1','make' => 'FOTON'),
            array('type_id' => '1','make' => 'FREIGHTLINER'),
            array('type_id' => '1','make' => 'FRUEHAUF'),
            array('type_id' => '1','make' => 'GRW'),
            array('type_id' => '1','make' => 'GT'),
            array('type_id' => '1','make' => 'GRAY & ADAMS'),
            array('type_id' => '1','make' => 'HAKO'),
            array('type_id' => '1','make' => 'HATFIELD'),
            array('type_id' => '1','make' => 'HEIL'),
            array('type_id' => '1','make' => 'HENRED FREUHAUF'),
            array('type_id' => '1','make' => 'HINO'),
            array('type_id' => '1','make' => 'HOME BUILT'),
            array('type_id' => '1','make' => 'HOMEZ'),
            array('type_id' => '1','make' => 'HOYNER'),
            array('type_id' => '1','make' => 'INTERNATIONAL'),
            array('type_id' => '1','make' => 'INTERNATIONAL EAGLE'),
            array('type_id' => '1','make' => 'ISUZU'),
            array('type_id' => '1','make' => 'IVECO'),
            array('type_id' => '1','make' => 'JMC'),
            array('type_id' => '1','make' => 'JOHNSTON'),
            array('type_id' => '1','make' => 'KASSBOHRER'),
            array('type_id' => '1','make' => 'KEARNEY'),
            array('type_id' => '1','make' => 'KEL-BERG'),
            array('type_id' => '1','make' => 'KENWORTH'),
            array('type_id' => '1','make' => 'KING'),
            array('type_id' => '1','make' => 'KRAKER'),
            array('type_id' => '1','make' => 'KRONE'),
            array('type_id' => '1','make' => 'LDV'),
            array('type_id' => '1','make' => 'LAMBERET'),
            array('type_id' => '1','make' => 'LAWRENCE DAVID'),
            array('type_id' => '1','make' => 'LEGRAS'),
            array('type_id' => '1','make' => 'LEYLAND'),
            array('type_id' => '1','make' => 'LEYLAND DAF'),
            array('type_id' => '1','make' => 'M & G'),
            array('type_id' => '1','make' => 'MAN'),
            array('type_id' => '1','make' => 'MACK'),
            array('type_id' => '1','make' => 'MAISONNEUVE'),
            array('type_id' => '1','make' => 'MAXILODE'),
            array('type_id' => '1','make' => 'MCCAULEY'),
            array('type_id' => '1','make' => 'MERCEDES-BENZ'),
            array('type_id' => '1','make' => 'MICHIELETTO'),
            array('type_id' => '1','make' => 'MITSUBISHI'),
            array('type_id' => '1','make' => 'MONTRACON'),
            array('type_id' => '1','make' => 'MOTOTRAIL'),
            array('type_id' => '1','make' => 'MULDOON'),
            array('type_id' => '1','make' => 'NICOLAS'),
            array('type_id' => '1','make' => 'NISSAN'),
            array('type_id' => '1','make' => 'NOOTEBOOM'),
            array('type_id' => '1','make' => 'OLDBURY'),
            array('type_id' => '1','make' => 'OLYMPIA'),
            array('type_id' => '1','make' => 'OPTARE'),
            array('type_id' => '1','make' => 'OVERLANDER'),
            array('type_id' => '1','make' => 'PARAMOUNT'),
            array('type_id' => '1','make' => 'PETERBILT'),
            array('type_id' => '1','make' => 'POOLE'),
            array('type_id' => '1','make' => 'POWERSTAR'),
            array('type_id' => '1','make' => 'PR TRAILERS'),
            array('type_id' => '1','make' => 'RGM'),
            array('type_id' => '1','make' => 'RSA'),
            array('type_id' => '1','make' => 'RENAULT'),
            array('type_id' => '1','make' => 'ROME'),
            array('type_id' => '1','make' => 'RONDEBULT'),
            array('type_id' => '1','make' => 'ROTHDEAN'),
            array('type_id' => '1','make' => 'SDC'),
            array('type_id' => '1','make' => 'SA TRUCK BODIES'),
            array('type_id' => '1','make' => 'SAMAG'),
            array('type_id' => '1','make' => 'SAMIL'),
            array('type_id' => '1','make' => 'SAMRO'),
            array('type_id' => '1','make' => 'SCAMMELL'),
            array('type_id' => '1','make' => 'SCANIA'),
            array('type_id' => '1','make' => 'SCARAB'),
            array('type_id' => '1','make' => 'SCHMITZ'),
            array('type_id' => '1','make' => 'SEDDON ATKINSON'),
            array('type_id' => '1','make' => 'SERCO'),
            array('type_id' => '1','make' => 'SWAN'),
            array('type_id' => '1','make' => 'TALBERT'),
            array('type_id' => '1','make' => 'TANK CLINIC'),
            array('type_id' => '1','make' => 'TASKER'),
            array('type_id' => '1','make' => 'TATA'),
            array('type_id' => '1','make' => 'TERBERG'),
            array('type_id' => '1','make' => 'TIDD'),
            array('type_id' => '1','make' => 'TINSLEY'),
            array('type_id' => '1','make' => 'TOP TRAILERS'),
            array('type_id' => '1','make' => 'TRAILERKING'),
            array('type_id' => '1','make' => 'TUXFORD'),
            array('type_id' => '1','make' => 'UBT'),
            array('type_id' => '1','make' => 'UD'),
            array('type_id' => '1','make' => 'UNITED'),
            array('type_id' => '1','make' => 'VAN HOOL'),
            array('type_id' => '1','make' => 'VOLVO'),
            array('type_id' => '1','make' => 'WEIGHTLIFTER'),
            array('type_id' => '1','make' => 'WEIGHTMASTER'),
            array('type_id' => '1','make' => 'WESTERN STAR'),
            array('type_id' => '1','make' => 'WHALE'),
            array('type_id' => '1','make' => 'WHEELBASE'),
            array('type_id' => '1','make' => 'WHITEHEAD'),
            array('type_id' => '1','make' => 'WILCOX'),
            array('type_id' => '1','make' => 'WILSON'),
            array('type_id' => '1','make' => 'YORK'),
            array('type_id' => '2','make' => 'ACM'),
            array('type_id' => '2','make' => 'AG'),
            array('type_id' => '2','make' => 'AW'),
            array('type_id' => '2','make' => 'ABELCO'),
            array('type_id' => '2','make' => 'ACE'),
            array('type_id' => '2','make' => 'ACERA'),
            array('type_id' => '2','make' => 'AGROMATIC'),
            array('type_id' => '2','make' => 'AHLMANN'),
            array('type_id' => '2','make' => 'AICHI'),
            array('type_id' => '2','make' => 'AIRMAN'),
            array('type_id' => '2','make' => 'AIRQUICK'),
            array('type_id' => '2','make' => 'AKERMAN'),
            array('type_id' => '2','make' => 'ALLATT'),
            array('type_id' => '2','make' => 'ALLIED'),
            array('type_id' => '2','make' => 'ALLIS'),
            array('type_id' => '2','make' => 'ALLU'),
            array('type_id' => '2','make' => 'AMCO VEBA'),
            array('type_id' => '2','make' => 'AMMANN'),
            array('type_id' => '2','make' => 'AMMANN-YANMAR'),
            array('type_id' => '2','make' => 'APPLIED'),
            array('type_id' => '2','make' => 'ARMANNI'),
            array('type_id' => '2','make' => 'ATILA'),
            array('type_id' => '2','make' => 'ATLAS'),
            array('type_id' => '2','make' => 'ATLAS COPCO'),
            array('type_id' => '2','make' => 'AUGERTORQUE'),
            array('type_id' => '2','make' => 'AUSA'),
            array('type_id' => '2','make' => 'AVANT'),
            array('type_id' => '2','make' => 'AVELING BARFORD'),
            array('type_id' => '2','make' => 'AVIA'),
            array('type_id' => '2','make' => 'BAV'),
            array('type_id' => '2','make' => 'BJD'),
            array('type_id' => '2','make' => 'BANDIT'),
            array('type_id' => '2','make' => 'BARFORD'),
            array('type_id' => '2','make' => 'BATESON'),
            array('type_id' => '2','make' => 'BAUMASCHINEN'),
            array('type_id' => '2','make' => 'BEARCAT'),
            array('type_id' => '2','make' => 'BELAZ'),
            array('type_id' => '2','make' => 'BELL'),
            array('type_id' => '2','make' => 'BELLE'),
            array('type_id' => '2','make' => 'BENATI'),
            array('type_id' => '2','make' => 'BENFORD'),
            array('type_id' => '2','make' => 'BENFRA'),
            array('type_id' => '2','make' => 'BENMAC'),
            array('type_id' => '2','make' => 'BENMAG'),
            array('type_id' => '2','make' => 'BERCO'),
            array('type_id' => '2','make' => 'BIG FLOAT'),
            array('type_id' => '2','make' => 'BIGAB'),
            array('type_id' => '2','make' => 'BITELLI'),
            array('type_id' => '2','make' => 'BL PEGSON'),
            array('type_id' => '2','make' => 'BLAW KNOX'),
            array('type_id' => '2','make' => 'BOBCAT'),
            array('type_id' => '2','make' => 'BOKI'),
            array('type_id' => '2','make' => 'BOMAG'),
            array('type_id' => '2','make' => 'BOSCH'),
            array('type_id' => '2','make' => 'BOSS'),
            array('type_id' => '2','make' => 'BRAYT'),
            array('type_id' => '2','make' => 'BRIAN JAMES'),
            array('type_id' => '2','make' => 'BROKK'),
            array('type_id' => '2','make' => 'BROWN LENNOX'),
            array('type_id' => '2','make' => 'BUCYRUS ERIE'),
            array('type_id' => '2','make' => 'BUMAR'),
            array('type_id' => '2','make' => 'CAESAR'),
            array('type_id' => '2','make' => 'CARTER'),
            array('type_id' => '2','make' => 'CASE'),
            array('type_id' => '2','make' => 'CASE IH'),
            array('type_id' => '2','make' => 'CATERPILLAR'),
            array('type_id' => '2','make' => 'CAUTRAC'),
            array('type_id' => '2','make' => 'CEBORA'),
            array('type_id' => '2','make' => 'CHALLENGER'),
            array('type_id' => '2','make' => 'CHIEFTAIN'),
            array('type_id' => '2','make' => 'CHTZ'),
            array('type_id' => '2','make' => 'CLAAS'),
            array('type_id' => '2','make' => 'CLARK'),
            array('type_id' => '2','make' => 'COLCHESTER'),
            array('type_id' => '2','make' => 'COLES'),
            array('type_id' => '2','make' => 'COLMAR'),
            array('type_id' => '2','make' => 'COMPARE'),
            array('type_id' => '2','make' => 'CONTAINEX'),
            array('type_id' => '2','make' => 'CORMACH'),
            array('type_id' => '2','make' => 'CUMMINS'),
            array('type_id' => '2','make' => 'CUTHBERTSON'),
            array('type_id' => '2','make' => 'DAEWOO'),
            array('type_id' => '2','make' => 'DALIAN'),
            array('type_id' => '2','make' => 'DEMAG'),
            array('type_id' => '2','make' => 'DENNISON'),
            array('type_id' => '2','make' => 'DESTA'),
            array('type_id' => '2','make' => 'DEZZI'),
            array('type_id' => '2','make' => 'DITCH WITCH'),
            array('type_id' => '2','make' => 'DOOSAN'),
            array('type_id' => '2','make' => 'DORMAN'),
            array('type_id' => '2','make' => 'DOSCO'),
            array('type_id' => '2','make' => 'DRESSER'),
            array('type_id' => '2','make' => 'DYNAPAC'),
            array('type_id' => '2','make' => 'EDER'),
            array('type_id' => '2','make' => 'EFFER'),
            array('type_id' => '2','make' => 'ENGSTROM'),
            array('type_id' => '2','make' => 'ETEC'),
            array('type_id' => '2','make' => 'EUCLID'),
            array('type_id' => '2','make' => 'EURO TOWERS'),
            array('type_id' => '2','make' => 'EUROCOMACH'),
            array('type_id' => '2','make' => 'EUROMEC'),
            array('type_id' => '2','make' => 'EXTEC'),
            array('type_id' => '2','make' => 'FANTUZZI'),
            array('type_id' => '2','make' => 'FASSI'),
            array('type_id' => '2','make' => 'FAYMONVILLE'),
            array('type_id' => '2','make' => 'FERMEC'),
            array('type_id' => '2','make' => 'FG WILSON'),
            array('type_id' => '2','make' => 'FIAT-HITACHI'),
            array('type_id' => '2','make' => 'FINLAY'),
            array('type_id' => '2','make' => 'FIORI'),
            array('type_id' => '2','make' => 'FORD'),
            array('type_id' => '2','make' => 'FOTON'),
            array('type_id' => '2','make' => 'FRUEHAUF'),
            array('type_id' => '2','make' => 'FUCHS'),
            array('type_id' => '2','make' => 'FUGONG'),
            array('type_id' => '2','make' => 'FURUKAWA'),
            array('type_id' => '2','make' => 'FYSON'),
            array('type_id' => '2','make' => 'GP'),
            array('type_id' => '2','make' => 'GALION'),
            array('type_id' => '2','make' => 'GALLMAC'),
            array('type_id' => '2','make' => 'GEHL'),
            array('type_id' => '2','make' => 'GEHLMAX'),
            array('type_id' => '2','make' => 'GENIE'),
            array('type_id' => '2','make' => 'GISEBO'),
            array('type_id' => '2','make' => 'GOLDHOFER'),
            array('type_id' => '2','make' => 'GOODWIN BARSBY'),
            array('type_id' => '2','make' => 'GORANSONS'),
            array('type_id' => '2','make' => 'GRADEMASTER'),
            array('type_id' => '2','make' => 'GROVE'),
            array('type_id' => '2','make' => 'GROVLING'),
            array('type_id' => '2','make' => 'GUIDETTI'),
            array('type_id' => '2','make' => 'HMF'),
            array('type_id' => '2','make' => 'HPC'),
            array('type_id' => '2','make' => 'HSW'),
            array('type_id' => '2','make' => 'HAADFIELD'),
            array('type_id' => '2','make' => 'HALLA'),
            array('type_id' => '2','make' => 'HAMM'),
            array('type_id' => '2','make' => 'HANIX'),
            array('type_id' => '2','make' => 'HANOMAG'),
            array('type_id' => '2','make' => 'HARBEN'),
            array('type_id' => '2','make' => 'HARTL'),
            array('type_id' => '2','make' => 'HAULT-BAK'),
            array('type_id' => '2','make' => 'HAZEMAG'),
            array('type_id' => '2','make' => 'HAZLEWOOD'),
            array('type_id' => '2','make' => 'HENLEY'),
            array('type_id' => '2','make' => 'HIDROMEK'),
            array('type_id' => '2','make' => 'HIMOINSA'),
            array('type_id' => '2','make' => 'HINOWA'),
            array('type_id' => '2','make' => 'HITACHI'),
            array('type_id' => '2','make' => 'HOLDER'),
            array('type_id' => '2','make' => 'HUDDIG'),
            array('type_id' => '2','make' => 'HUMBAUR'),
            array('type_id' => '2','make' => 'HYCO'),
            array('type_id' => '2','make' => 'HYDR'),
            array('type_id' => '2','make' => 'HYDREMA'),
            array('type_id' => '2','make' => 'HYMAC'),
            array('type_id' => '2','make' => 'HYMAX'),
            array('type_id' => '2','make' => 'HYSTER'),
            array('type_id' => '2','make' => 'HYUNDAI'),
            array('type_id' => '2','make' => 'IFOR WILLIAMS'),
            array('type_id' => '2','make' => 'INDECO'),
            array('type_id' => '2','make' => 'INDESPENSION'),
            array('type_id' => '2','make' => 'INGERSOLL RAND'),
            array('type_id' => '2','make' => 'ISEKI'),
            array('type_id' => '2','make' => 'ITALMACCHINE'),
            array('type_id' => '2','make' => 'JCB'),
            array('type_id' => '2','make' => 'JCM'),
            array('type_id' => '2','make' => 'JLG'),
            array('type_id' => '2','make' => 'JAMES'),
            array('type_id' => '2','make' => 'JENSON'),
            array('type_id' => '2','make' => 'JOHN DEERE'),
            array('type_id' => '2','make' => 'JOLLY'),
            array('type_id' => '2','make' => 'JUMZ'),
            array('type_id' => '2','make' => 'JUNGHEINRICH'),
            array('type_id' => '2','make' => 'KMB'),
            array('type_id' => '2','make' => 'KAELBLE'),
            array('type_id' => '2','make' => 'KAESER'),
            array('type_id' => '2','make' => 'KAISER'),
            array('type_id' => '2','make' => 'KALMAR'),
            array('type_id' => '2','make' => 'KAMATSU'),
            array('type_id' => '2','make' => 'KAMAZ'),
            array('type_id' => '2','make' => 'KARCHER'),
            array('type_id' => '2','make' => 'KATO'),
            array('type_id' => '2','make' => 'KAWASAKI'),
            array('type_id' => '2','make' => 'KOBELCO'),
            array('type_id' => '2','make' => 'KOCKUM'),
            array('type_id' => '2','make' => 'KOMATSU'),
            array('type_id' => '2','make' => 'KRAMER'),
            array('type_id' => '2','make' => 'KRAZ'),
            array('type_id' => '2','make' => 'KRUPP'),
            array('type_id' => '2','make' => 'KUBOTA'),
            array('type_id' => '2','make' => 'KUE KEN'),
            array('type_id' => '2','make' => 'LANCER BOSS'),
            array('type_id' => '2','make' => 'LANNEN'),
            array('type_id' => '2','make' => 'LANZ'),
            array('type_id' => '2','make' => 'LEHNHOFF'),
            array('type_id' => '2','make' => 'LEHNOSS'),
            array('type_id' => '2','make' => 'LIAZ'),
            array('type_id' => '2','make' => 'LIBRA'),
            array('type_id' => '2','make' => 'LIEBHERR'),
            array('type_id' => '2','make' => 'LIFTON'),
            array('type_id' => '2','make' => 'LINDE'),
            array('type_id' => '2','make' => 'LIUGONG'),
            array('type_id' => '2','make' => 'LJUNGBY'),
            array('type_id' => '2','make' => 'LODICO'),
            array('type_id' => '2','make' => 'LONGGONG'),
            array('type_id' => '2','make' => 'LUIGONG'),
            array('type_id' => '2','make' => 'LULL'),
            array('type_id' => '2','make' => 'LUNDBERG'),
            array('type_id' => '2','make' => 'MAC'),
            array('type_id' => '2','make' => 'MAX'),
            array('type_id' => '2','make' => 'MAZ'),
            array('type_id' => '2','make' => 'MB'),
            array('type_id' => '2','make' => 'MBU'),
            array('type_id' => '2','make' => 'MV'),
            array('type_id' => '2','make' => 'MACMOTER'),
            array('type_id' => '2','make' => 'MACNAY'),
            array('type_id' => '2','make' => 'MANITOU'),
            array('type_id' => '2','make' => 'MARINI'),
            array('type_id' => '2','make' => 'MASKIN MEKANO'),
            array('type_id' => '2','make' => 'MASSEY FERGUSON'),
            array('type_id' => '2','make' => 'MAST'),
            array('type_id' => '2','make' => 'MATBRO'),
            array('type_id' => '2','make' => 'MATTSSON'),
            array('type_id' => '2','make' => 'MECALAC'),
            array('type_id' => '2','make' => 'MENZI MUCK'),
            array('type_id' => '2','make' => 'MERLO'),
            array('type_id' => '2','make' => 'MESSERSI'),
            array('type_id' => '2','make' => 'METSO'),
            array('type_id' => '2','make' => 'MICHIGAN'),
            array('type_id' => '2','make' => 'MITSUBISHI'),
            array('type_id' => '2','make' => 'MOCKELN'),
            array('type_id' => '2','make' => 'MOELVEN'),
            array('type_id' => '2','make' => 'MOGURDSHAMMAR'),
            array('type_id' => '2','make' => 'MONTABERT'),
            array('type_id' => '2','make' => 'MOROOKA'),
            array('type_id' => '2','make' => 'MOXY'),
            array('type_id' => '2','make' => 'MUIR HILL'),
            array('type_id' => '2','make' => 'MUSTANG'),
            array('type_id' => '2','make' => 'NCK'),
            array('type_id' => '2','make' => 'NPK'),
            array('type_id' => '2','make' => 'NAGANO'),
            array('type_id' => '2','make' => 'NANTE'),
            array('type_id' => '2','make' => 'NEUMEIER'),
            array('type_id' => '2','make' => 'NEUSON'),
            array('type_id' => '2','make' => 'NEW HOLLAND'),
            array('type_id' => '2','make' => 'NIFTYLIFT'),
            array('type_id' => '2','make' => 'NISSAN'),
            array('type_id' => '2','make' => 'NOBAS'),
            array('type_id' => '2','make' => 'NORDBERG'),
            array('type_id' => '2','make' => 'NORDVERK'),
            array('type_id' => '2','make' => 'NOTEBOOM'),
            array('type_id' => '2','make' => 'NOVOTNY'),
            array('type_id' => '2','make' => 'OLIFANT'),
            array('type_id' => '2','make' => 'OLYMPIAN'),
            array('type_id' => '2','make' => 'ORENSTEIN AND KOPPEL'),
            array('type_id' => '2','make' => 'OSBORN'),
            array('type_id' => '2','make' => 'OSHKOSH'),
            array('type_id' => '2','make' => 'PMI'),
            array('type_id' => '2','make' => 'PPM'),
            array('type_id' => '2','make' => 'PALFINGER'),
            array('type_id' => '2','make' => 'PARKER'),
            array('type_id' => '2','make' => 'PAUS'),
            array('type_id' => '2','make' => 'PAYLOADER'),
            array('type_id' => '2','make' => 'PEGSON'),
            array('type_id' => '2','make' => 'PEL-JOB'),
            array('type_id' => '2','make' => 'PETBOW'),
            array('type_id' => '2','make' => 'PIKET'),
            array('type_id' => '2','make' => 'PILOT CRUSHTEC'),
            array('type_id' => '2','make' => 'POCLAIN'),
            array('type_id' => '2','make' => 'POWERSCREEN'),
            array('type_id' => '2','make' => 'PRIESTMAN'),
            array('type_id' => '2','make' => 'PROBST'),
            array('type_id' => '2','make' => 'PROTEC'),
            array('type_id' => '2','make' => 'PUTZMEISTER'),
            array('type_id' => '2','make' => 'QUICKE'),
            array('type_id' => '2','make' => 'RAYCO'),
            array('type_id' => '2','make' => 'RED RHINO'),
            array('type_id' => '2','make' => 'REMU'),
            array('type_id' => '2','make' => 'REX'),
            array('type_id' => '2','make' => 'REXWORKS'),
            array('type_id' => '2','make' => 'RONDEBULT'),
            array('type_id' => '2','make' => 'ROTAR'),
            array('type_id' => '2','make' => 'RUBBLE MASTER'),
            array('type_id' => '2','make' => 'RUSTON BUCYRUS'),
            array('type_id' => '2','make' => 'RUTHEMEYER'),
            array('type_id' => '2','make' => 'SDC'),
            array('type_id' => '2','make' => 'SEB'),
            array('type_id' => '2','make' => 'SMC'),
            array('type_id' => '2','make' => 'SAMAG'),
            array('type_id' => '2','make' => 'SAMBRON'),
            array('type_id' => '2','make' => 'SAMSUNG'),
            array('type_id' => '2','make' => 'SAMUK'),
            array('type_id' => '2','make' => 'SANDERSON'),
            array('type_id' => '2','make' => 'SANY'),
            array('type_id' => '2','make' => 'SCHAEFF'),
            array('type_id' => '2','make' => 'SCHMIDT'),
            array('type_id' => '2','make' => 'SCHMITZ'),
            array('type_id' => '2','make' => 'SCORPION'),
            array('type_id' => '2','make' => 'SENNEBOGEN'),
            array('type_id' => '2','make' => 'SHANTUI'),
            array('type_id' => '2','make' => 'SIMESA'),
            array('type_id' => '2','make' => 'SIMON BOXER'),
            array('type_id' => '2','make' => 'SINOWAY'),
            array('type_id' => '2','make' => 'SISIS'),
            array('type_id' => '2','make' => 'SISU'),
            array('type_id' => '2','make' => 'SKY JACK'),
            array('type_id' => '2','make' => 'SKY KING'),
            array('type_id' => '2','make' => 'SOLMEC'),
            array('type_id' => '2','make' => 'STAR'),
            array('type_id' => '2','make' => 'STAVOSTROJ'),
            array('type_id' => '2','make' => 'STIHL'),
            array('type_id' => '2','make' => 'STILL'),
            array('type_id' => '2','make' => 'SULLAIR'),
            array('type_id' => '2','make' => 'SUMITOMO'),
            array('type_id' => '2','make' => 'SUMO'),
            array('type_id' => '2','make' => 'SUNWARD'),
            array('type_id' => '2','make' => 'SVEDALA'),
            array('type_id' => '2','make' => 'SYMONDS'),
            array('type_id' => '2','make' => 'TCM'),
            array('type_id' => '2','make' => 'TAARUP'),
            array('type_id' => '2','make' => 'TADANO'),
            array('type_id' => '2','make' => 'TAKE-JOB'),
            array('type_id' => '2','make' => 'TAKEUCHI'),
            array('type_id' => '2','make' => 'TAKRAF'),
            array('type_id' => '2','make' => 'TATRA'),
            array('type_id' => '2','make' => 'TELEPORTER'),
            array('type_id' => '2','make' => 'TELSMITH'),
            array('type_id' => '2','make' => 'TENNANT'),
            array('type_id' => '2','make' => 'TEREX'),
            array('type_id' => '2','make' => 'THOMAS'),
            array('type_id' => '2','make' => 'THWAITES'),
            array('type_id' => '2','make' => 'TOYOTA'),
            array('type_id' => '2','make' => 'TROMMEL'),
            array('type_id' => '2','make' => 'UNEX'),
            array('type_id' => '2','make' => 'UNIMOG'),
            array('type_id' => '2','make' => 'UTILITY'),
            array('type_id' => '2','make' => 'VALMET'),
            array('type_id' => '2','make' => 'VEEKMAS'),
            array('type_id' => '2','make' => 'VENIERI'),
            array('type_id' => '2','make' => 'VERMEER'),
            array('type_id' => '2','make' => 'VIBROMAX'),
            array('type_id' => '2','make' => 'VICKERS'),
            array('type_id' => '2','make' => 'VOGELE'),
            array('type_id' => '2','make' => 'VOLVO'),
            array('type_id' => '2','make' => 'WARRIOR'),
            array('type_id' => '2','make' => 'WARYNSKI'),
            array('type_id' => '2','make' => 'WEBER'),
            array('type_id' => '2','make' => 'WEIMAR'),
            array('type_id' => '2','make' => 'WESTERN'),
            array('type_id' => '2','make' => 'WILLE'),
            array('type_id' => '2','make' => 'WINGET'),
            array('type_id' => '2','make' => 'WIRTGEN'),
            array('type_id' => '2','make' => 'XCG'),
            array('type_id' => '2','make' => 'YTO'),
            array('type_id' => '2','make' => 'YAMAGUCHI'),
            array('type_id' => '2','make' => 'YANMAR'),
            array('type_id' => '2','make' => 'YUCHAI'),
            array('type_id' => '2','make' => 'ZIL'),
            array('type_id' => '2','make' => 'ZTS'),
            array('type_id' => '2','make' => 'ZEPPELIN'),
            array('type_id' => '2','make' => 'ZETTELMEYER'),
            array('type_id' => '3','make' => 'ABBEY'),
            array('type_id' => '3','make' => 'ACCORD'),
            array('type_id' => '3','make' => 'AEBI'),
            array('type_id' => '3','make' => 'AGCO'),
            array('type_id' => '3','make' => 'AGRIA'),
            array('type_id' => '3','make' => 'AGRICO'),
            array('type_id' => '3','make' => 'AGRIFULL'),
            array('type_id' => '3','make' => 'AGRIMASTER'),
            array('type_id' => '3','make' => 'AGRITEC'),
            array('type_id' => '3','make' => 'AGRO MASTER'),
            array('type_id' => '3','make' => 'AGROMATIC'),
            array('type_id' => '3','make' => 'ALBUT'),
            array('type_id' => '3','make' => 'ALLET'),
            array('type_id' => '3','make' => 'ALLIS CHALMERS'),
            array('type_id' => '3','make' => 'AMAZONE'),
            array('type_id' => '3','make' => 'ARGO'),
            array('type_id' => '3','make' => 'ASUKA'),
            array('type_id' => '3','make' => 'AVANT'),
            array('type_id' => '3','make' => 'AVTO'),
            array('type_id' => '3','make' => 'AW TRAILERS'),
            array('type_id' => '3','make' => 'BCS'),
            array('type_id' => '3','make' => 'BAILEY TRAILERS'),
            array('type_id' => '3','make' => 'BARGAM'),
            array('type_id' => '3','make' => 'BARREIROS'),
            array('type_id' => '3','make' => 'BEACHTECH'),
            array('type_id' => '3','make' => 'BEARCAT'),
            array('type_id' => '3','make' => 'BELARUS'),
            array('type_id' => '3','make' => 'BELL'),
            array('type_id' => '3','make' => 'BENASSI'),
            array('type_id' => '3','make' => 'BERTHOUD'),
            array('type_id' => '3','make' => 'BIMA'),
            array('type_id' => '3','make' => 'BLENCH'),
            array('type_id' => '3','make' => 'BOBCAT'),
            array('type_id' => '3','make' => 'BOLENS'),
            array('type_id' => '3','make' => 'BOLLAND'),
            array('type_id' => '3','make' => 'BOMFORD'),
            array('type_id' => '3','make' => 'BOSCH'),
            array('type_id' => '3','make' => 'BROWNS'),
            array('type_id' => '3','make' => 'BUCHER'),
            array('type_id' => '3','make' => 'BUHLER'),
            array('type_id' => '3','make' => 'CARLTON'),
            array('type_id' => '3','make' => 'CARRARO'),
            array('type_id' => '3','make' => 'CASE'),
            array('type_id' => '3','make' => 'CASE IH'),
            array('type_id' => '3','make' => 'CATERPILLAR'),
            array('type_id' => '3','make' => 'CENTRELINER'),
            array('type_id' => '3','make' => 'CHALLENGER'),
            array('type_id' => '3','make' => 'CHARTERHOUSE'),
            array('type_id' => '3','make' => 'CHECCHI AND MAGLI'),
            array('type_id' => '3','make' => 'CLAAS'),
            array('type_id' => '3','make' => 'COOKS'),
            array('type_id' => '3','make' => 'COUNTAX'),
            array('type_id' => '3','make' => 'COUNTY'),
            array('type_id' => '3','make' => 'COUSINS'),
            array('type_id' => '3','make' => 'CRISBOX'),
            array('type_id' => '3','make' => 'DW TOMLIN'),
            array('type_id' => '3','make' => 'DANAGRI-3S'),
            array('type_id' => '3','make' => 'DAVID BROWN'),
            array('type_id' => '3','make' => 'DENARDI'),
            array('type_id' => '3','make' => 'DEUTZ'),
            array('type_id' => '3','make' => 'DOPPSTADT'),
            array('type_id' => '3','make' => 'DOWDESWELL'),
            array('type_id' => '3','make' => 'DROTSKY'),
            array('type_id' => '3','make' => 'EBRO'),
            array('type_id' => '3','make' => 'EDLINGTON'),
            array('type_id' => '3','make' => 'EICHER'),
            array('type_id' => '3','make' => 'EINBOCK'),
            array('type_id' => '3','make' => 'ENERGREEN'),
            array('type_id' => '3','make' => 'ENOROSSI'),
            array('type_id' => '3','make' => 'ENTEC'),
            array('type_id' => '3','make' => 'ENVOY'),
            array('type_id' => '3','make' => 'EQUI-TREK'),
            array('type_id' => '3','make' => 'ETESIA'),
            array('type_id' => '3','make' => 'EUROPARD'),
            array('type_id' => '3','make' => 'EUROTRAC'),
            array('type_id' => '3','make' => 'FNR'),
            array('type_id' => '3','make' => 'FARM FORCE'),
            array('type_id' => '3','make' => 'FARMTRAC'),
            array('type_id' => '3','make' => 'FARMWRIGHT'),
            array('type_id' => '3','make' => 'FAUCHEUX'),
            array('type_id' => '3','make' => 'FELLA'),
            array('type_id' => '3','make' => 'FENDT'),
            array('type_id' => '3','make' => 'FERABOLI'),
            array('type_id' => '3','make' => 'FERRARI'),
            array('type_id' => '3','make' => 'FIAT'),
            array('type_id' => '3','make' => 'FIATAGRI'),
            array('type_id' => '3','make' => 'FLEMING'),
            array('type_id' => '3','make' => 'FORD'),
            array('type_id' => '3','make' => 'FORDSON'),
            array('type_id' => '3','make' => 'FORTSCHRITT'),
            array('type_id' => '3','make' => 'FOSTER'),
            array('type_id' => '3','make' => 'FOTON'),
            array('type_id' => '3','make' => 'FRASER'),
            array('type_id' => '3','make' => 'FULLER'),
            array('type_id' => '3','make' => 'GEM'),
            array('type_id' => '3','make' => 'GHL'),
            array('type_id' => '3','make' => 'GIANNI FERRARI'),
            array('type_id' => '3','make' => 'GOLDONI'),
            array('type_id' => '3','make' => 'GRAVELY'),
            array('type_id' => '3','make' => 'GRAYS'),
            array('type_id' => '3','make' => 'GREAT DANE'),
            array('type_id' => '3','make' => 'GREENMECH'),
            array('type_id' => '3','make' => 'GREGOIRE'),
            array('type_id' => '3','make' => 'GRIFFITHS'),
            array('type_id' => '3','make' => 'GRIMME'),
            array('type_id' => '3','make' => 'GULDNER'),
            array('type_id' => '3','make' => 'HSM'),
            array('type_id' => '3','make' => 'HALL'),
            array('type_id' => '3','make' => 'HANOMAG'),
            array('type_id' => '3','make' => 'HARDI'),
            array('type_id' => '3','make' => 'HAYTER'),
            array('type_id' => '3','make' => 'HERBST'),
            array('type_id' => '3','make' => 'HESSTON'),
            array('type_id' => '3','make' => 'HOLDER'),
            array('type_id' => '3','make' => 'HONDA'),
            array('type_id' => '3','make' => 'HORSCH'),
            array('type_id' => '3','make' => 'HOULE'),
            array('type_id' => '3','make' => 'HOWARD'),
            array('type_id' => '3','make' => 'HUNTON LEGG'),
            array('type_id' => '3','make' => 'HURLIMANN'),
            array('type_id' => '3','make' => 'HUSQAVARNA'),
            array('type_id' => '3','make' => 'IMT'),
            array('type_id' => '3','make' => 'IFOR WILLIAMS'),
            array('type_id' => '3','make' => 'INTERNATIONAL'),
            array('type_id' => '3','make' => 'ISEKI'),
            array('type_id' => '3','make' => 'ISUZU'),
            array('type_id' => '3','make' => 'JCB'),
            array('type_id' => '3','make' => 'JF'),
            array('type_id' => '3','make' => 'JPM'),
            array('type_id' => '3','make' => 'JWT'),
            array('type_id' => '3','make' => 'JACOBSEN'),
            array('type_id' => '3','make' => 'JEEP'),
            array('type_id' => '3','make' => 'JENSEN'),
            array('type_id' => '3','make' => 'JOHN DEERE'),
            array('type_id' => '3','make' => 'JOHNSON'),
            array('type_id' => '3','make' => 'JONSERED'),
            array('type_id' => '3','make' => 'JUMIL'),
            array('type_id' => '3','make' => 'KRM'),
            array('type_id' => '3','make' => 'KAWASAKI'),
            array('type_id' => '3','make' => 'KEENAN'),
            array('type_id' => '3','make' => 'KELTEC'),
            array('type_id' => '3','make' => 'KEN WOOTON'),
            array('type_id' => '3','make' => 'KIDD'),
            array('type_id' => '3','make' => 'KILWORTH'),
            array('type_id' => '3','make' => 'KIOTI'),
            array('type_id' => '3','make' => 'KIROVETS'),
            array('type_id' => '3','make' => 'KNOCHE'),
            array('type_id' => '3','make' => 'KOMATSU'),
            array('type_id' => '3','make' => 'KONGSKILDE'),
            array('type_id' => '3','make' => 'KRONE'),
            array('type_id' => '3','make' => 'KUBOTA'),
            array('type_id' => '3','make' => 'KUHN'),
            array('type_id' => '3','make' => 'KVERNELAND'),
            array('type_id' => '3','make' => 'KWIK CHIP'),
            array('type_id' => '3','make' => 'LAMBORGHINI'),
            array('type_id' => '3','make' => 'LAND ROVER'),
            array('type_id' => '3','make' => 'LANDINI'),
            array('type_id' => '3','make' => 'LANDLEGEND'),
            array('type_id' => '3','make' => 'LANDMEC'),
            array('type_id' => '3','make' => 'LARRINGTON'),
            array('type_id' => '3','make' => 'LASTEC'),
            array('type_id' => '3','make' => 'LAVERDA'),
            array('type_id' => '3','make' => 'LAWNFLITE'),
            array('type_id' => '3','make' => 'LAWRENCE EDWARDS'),
            array('type_id' => '3','make' => 'LELY'),
            array('type_id' => '3','make' => 'LEMKIN'),
            array('type_id' => '3','make' => 'LEYLAND'),
            array('type_id' => '3','make' => 'LINDNER'),
            array('type_id' => '3','make' => 'MDW'),
            array('type_id' => '3','make' => 'MAHINDRA'),
            array('type_id' => '3','make' => 'MAJOR'),
            array('type_id' => '3','make' => 'MALGAR'),
            array('type_id' => '3','make' => 'MANITOU'),
            array('type_id' => '3','make' => 'MARSHALL'),
            array('type_id' => '3','make' => 'MARSTON'),
            array('type_id' => '3','make' => 'MASCHIO'),
            array('type_id' => '3','make' => 'MASSEY FERGUSON'),
            array('type_id' => '3','make' => 'MATBRO'),
            array('type_id' => '3','make' => 'MCCONNEL'),
            array('type_id' => '3','make' => 'MCCORMICK'),
            array('type_id' => '3','make' => 'MCHALE'),
            array('type_id' => '3','make' => 'MENGELE'),
            array('type_id' => '3','make' => 'MERCEDES-BENZ'),
            array('type_id' => '3','make' => 'MERLO'),
            array('type_id' => '3','make' => 'MITSUBISHI'),
            array('type_id' => '3','make' => 'MORBARK'),
            array('type_id' => '3','make' => 'MOROOKA'),
            array('type_id' => '3','make' => 'MOTRANSA-NUFFIELD'),
            array('type_id' => '3','make' => 'MUCKMASTER'),
            array('type_id' => '3','make' => 'MUIR HILL'),
            array('type_id' => '3','make' => 'MULTEC'),
            array('type_id' => '3','make' => 'NC ENGINEERING'),
            array('type_id' => '3','make' => 'NEW HOLLAND'),
            array('type_id' => '3','make' => 'NIBBI'),
            array('type_id' => '3','make' => 'NOBILI'),
            array('type_id' => '3','make' => 'NORTON'),
            array('type_id' => '3','make' => 'NUGENT'),
            array('type_id' => '3','make' => 'OM'),
            array('type_id' => '3','make' => 'OPICO'),
            array('type_id' => '3','make' => 'ORSI'),
            array('type_id' => '3','make' => 'OVERUM'),
            array('type_id' => '3','make' => 'PZ'),
            array('type_id' => '3','make' => 'PAOLI'),
            array('type_id' => '3','make' => 'PARMITER'),
            array('type_id' => '3','make' => 'PASQUALI'),
            array('type_id' => '3','make' => 'PERFECT'),
            array('type_id' => '3','make' => 'PICHON'),
            array('type_id' => '3','make' => 'POLARIS'),
            array('type_id' => '3','make' => 'PORT AGRIC'),
            array('type_id' => '3','make' => 'POTTINGER'),
            array('type_id' => '3','make' => 'PRIMEX'),
            array('type_id' => '3','make' => 'PRONAR'),
            array('type_id' => '3','make' => 'QUANTOCK'),
            array('type_id' => '3','make' => 'QUICKE'),
            array('type_id' => '3','make' => 'RABE'),
            array('type_id' => '3','make' => 'RANCH'),
            array('type_id' => '3','make' => 'RANSOME'),
            array('type_id' => '3','make' => 'RAYCO'),
            array('type_id' => '3','make' => 'RECO'),
            array('type_id' => '3','make' => 'REDROCK'),
            array('type_id' => '3','make' => 'REEKI'),
            array('type_id' => '3','make' => 'REFORM'),
            array('type_id' => '3','make' => 'RENAULT'),
            array('type_id' => '3','make' => 'RICHARD LARRINGTON'),
            array('type_id' => '3','make' => 'RICHARD WESTERN'),
            array('type_id' => '3','make' => 'RITCHIE'),
            array('type_id' => '3','make' => 'RITLEE'),
            array('type_id' => '3','make' => 'ROGUE STEEL'),
            array('type_id' => '3','make' => 'ROLLAND'),
            array('type_id' => '3','make' => 'RUSCON'),
            array('type_id' => '3','make' => 'RYETEC'),
            array('type_id' => '3','make' => 'SA WONDER'),
            array('type_id' => '3','make' => 'SALOP'),
            array('type_id' => '3','make' => 'SAMCO'),
            array('type_id' => '3','make' => 'SAME'),
            array('type_id' => '3','make' => 'SAMSON'),
            array('type_id' => '3','make' => 'SCHLATER'),
            array('type_id' => '3','make' => 'SCHLIESING'),
            array('type_id' => '3','make' => 'SHELBOURNE REYNOLDS'),
            array('type_id' => '3','make' => 'SHIBAURA'),
            array('type_id' => '3','make' => 'SIMBA'),
            array('type_id' => '3','make' => 'SIMSE'),
            array('type_id' => '3','make' => 'SIROMER'),
            array('type_id' => '3','make' => 'SITREX'),
            array('type_id' => '3','make' => 'SMYTH'),
            array('type_id' => '3','make' => 'SOMECA'),
            array('type_id' => '3','make' => 'SPALDINGS'),
            array('type_id' => '3','make' => 'SPEARHEAD'),
            array('type_id' => '3','make' => 'STAALMEESTER'),
            array('type_id' => '3','make' => 'STAR'),
            array('type_id' => '3','make' => 'STEIGER'),
            array('type_id' => '3','make' => 'STEYR'),
            array('type_id' => '3','make' => 'STICO'),
            array('type_id' => '3','make' => 'STOLL'),
            array('type_id' => '3','make' => 'STRAUTMANN'),
            array('type_id' => '3','make' => 'STROTH'),
            array('type_id' => '3','make' => 'SUKI'),
            array('type_id' => '3','make' => 'SUZUKI'),
            array('type_id' => '3','make' => 'SYSTRA'),
            array('type_id' => '3','make' => 'TAARUP'),
            array('type_id' => '3','make' => 'TANCO'),
            array('type_id' => '3','make' => 'TEAGLE'),
            array('type_id' => '3','make' => 'TECNOMA'),
            array('type_id' => '3','make' => 'TERAW'),
            array('type_id' => '3','make' => 'TERRAVAC'),
            array('type_id' => '3','make' => 'TILLMASTER'),
            array('type_id' => '3','make' => 'TIMBERJACK'),
            array('type_id' => '3','make' => 'TIMBERWOLF'),
            array('type_id' => '3','make' => 'TORO'),
            array('type_id' => '3','make' => 'TOSELLI'),
            array('type_id' => '3','make' => 'TOWNSUNNY'),
            array('type_id' => '3','make' => 'TOYOTA'),
            array('type_id' => '3','make' => 'TRAKTORENWERK SCHONEBECK'),
            array('type_id' => '3','make' => 'TRE EMME'),
            array('type_id' => '3','make' => 'TRIOLIET'),
            array('type_id' => '3','make' => 'TURNER'),
            array('type_id' => '3','make' => 'TWOSE'),
            array('type_id' => '3','make' => 'TWYMAN'),
            array('type_id' => '3','make' => 'TYM'),
            array('type_id' => '3','make' => 'UNIMOG'),
            array('type_id' => '3','make' => 'UNIVERSAL'),
            array('type_id' => '3','make' => 'URSUS'),
            array('type_id' => '3','make' => 'VADERSTAD'),
            array('type_id' => '3','make' => 'VALMET'),
            array('type_id' => '3','make' => 'VALPADANA'),
            array('type_id' => '3','make' => 'VALTRA'),
            array('type_id' => '3','make' => 'VELSA'),
            array('type_id' => '3','make' => 'VEMAC'),
            array('type_id' => '3','make' => 'VERMEER'),
            array('type_id' => '3','make' => 'VERSATILE'),
            array('type_id' => '3','make' => 'VICON'),
            array('type_id' => '3','make' => 'VIPER'),
            array('type_id' => '3','make' => 'VITHAR'),
            array('type_id' => '3','make' => 'VODERSTAD'),
            array('type_id' => '3','make' => 'VOLVO'),
            array('type_id' => '3','make' => 'WARWICK'),
            array('type_id' => '3','make' => 'WATSON'),
            array('type_id' => '3','make' => 'WATVEARE'),
            array('type_id' => '3','make' => 'WEAVING'),
            array('type_id' => '3','make' => 'WEBB'),
            array('type_id' => '3','make' => 'WELGER'),
            array('type_id' => '3','make' => 'WESSEX'),
            array('type_id' => '3','make' => 'WEST'),
            array('type_id' => '3','make' => 'WESTERN'),
            array('type_id' => '3','make' => 'WESTWOOD'),
            array('type_id' => '3','make' => 'WHALE'),
            array('type_id' => '3','make' => 'WIEDENMANN'),
            array('type_id' => '3','make' => 'WILLIBALD'),
            array('type_id' => '3','make' => 'WOODS'),
            array('type_id' => '3','make' => 'WOOTON'),
            array('type_id' => '3','make' => 'WRIGHT'),
            array('type_id' => '3','make' => 'YTO'),
            array('type_id' => '3','make' => 'YAMAHA'),
            array('type_id' => '3','make' => 'YANMAR'),
            array('type_id' => '3','make' => 'ZETOR'),
            array('type_id' => '4','make' => 'AC'),
            array('type_id' => '4','make' => 'ARO'),
            array('type_id' => '4','make' => 'ABARTH'),
            array('type_id' => '4','make' => 'AIXAM'),
            array('type_id' => '4','make' => 'ALFA ROMEO'),
            array('type_id' => '4','make' => 'ALLARD'),
            array('type_id' => '4','make' => 'ALPINE'),
            array('type_id' => '4','make' => 'ALVIS'),
            array('type_id' => '4','make' => 'ANZANI'),
            array('type_id' => '4','make' => 'ARIEL'),
            array('type_id' => '4','make' => 'ARM SIDDELEY'),
            array('type_id' => '4','make' => 'ARNOLT-BRISTOL'),
            array('type_id' => '4','make' => 'ASCARI'),
            array('type_id' => '4','make' => 'ASIA'),
            array('type_id' => '4','make' => 'ASTON MARTIN'),
            array('type_id' => '4','make' => 'AUBURN'),
            array('type_id' => '4','make' => 'AUDI'),
            array('type_id' => '4','make' => 'AUSTIN'),
            array('type_id' => '4','make' => 'AUTO UNION'),
            array('type_id' => '4','make' => 'BAC'),
            array('type_id' => '4','make' => 'BMW'),
            array('type_id' => '4','make' => 'BEAUFORD'),
            array('type_id' => '4','make' => 'BELSIZE'),
            array('type_id' => '4','make' => 'BENTLEY'),
            array('type_id' => '4','make' => 'BITTER'),
            array('type_id' => '4','make' => 'BOND'),
            array('type_id' => '4','make' => 'BORGWARD'),
            array('type_id' => '4','make' => 'BOWLER'),
            array('type_id' => '4','make' => 'BRAMWITH'),
            array('type_id' => '4','make' => 'BRISTOL'),
            array('type_id' => '4','make' => 'BROOKE'),
            array('type_id' => '4','make' => 'BUCKINGHAM'),
            array('type_id' => '4','make' => 'BUGATTI'),
            array('type_id' => '4','make' => 'BUICK'),
            array('type_id' => '4','make' => 'CADILLAC'),
            array('type_id' => '4','make' => 'CAPARO'),
            array('type_id' => '4','make' => 'CARBODIES'),
            array('type_id' => '4','make' => 'CATERHAM'),
            array('type_id' => '4','make' => 'CHESIL'),
            array('type_id' => '4','make' => 'CHEVROLET'),
            array('type_id' => '4','make' => 'CHEVRON'),
            array('type_id' => '4','make' => 'CHRYS AUS'),
            array('type_id' => '4','make' => 'CHRYSLER'),
            array('type_id' => '4','make' => 'CITROEN'),
            array('type_id' => '4','make' => 'COLEMAN MILNE'),
            array('type_id' => '4','make' => 'CONNAUGHT'),
            array('type_id' => '4','make' => 'CORVETTE'),
            array('type_id' => '4','make' => 'CROSSLEY'),
            array('type_id' => '4','make' => 'CUSTOM VEHICLE'),
            array('type_id' => '4','make' => 'DAF'),
            array('type_id' => '4','make' => 'DS'),
            array('type_id' => '4','make' => 'DACIA'),
            array('type_id' => '4','make' => 'DAEWOO'),
            array('type_id' => '4','make' => 'DAIHATSU'),
            array('type_id' => '4','make' => 'DAIMLER'),
            array('type_id' => '4','make' => 'DALLAS'),
            array('type_id' => '4','make' => 'DATSUN'),
            array('type_id' => '4','make' => 'DAX'),
            array('type_id' => '4','make' => 'DE TOMASO'),
            array('type_id' => '4','make' => 'DELOREAN'),
            array('type_id' => '4','make' => 'DODGE'),
            array('type_id' => '4','make' => 'ERA'),
            array('type_id' => '4','make' => 'EDEL'),
            array('type_id' => '4','make' => 'EFFEDI'),
            array('type_id' => '4','make' => 'EUROBRUN'),
            array('type_id' => '4','make' => 'EXCALIBUR'),
            array('type_id' => '4','make' => 'FRS'),
            array('type_id' => '4','make' => 'FSO'),
            array('type_id' => '4','make' => 'FACEL VEGA'),
            array('type_id' => '4','make' => 'FAIRTHORPE'),
            array('type_id' => '4','make' => 'FARBIO'),
            array('type_id' => '4','make' => 'FERRARI'),
            array('type_id' => '4','make' => 'FIAT'),
            array('type_id' => '4','make' => 'FISHER'),
            array('type_id' => '4','make' => 'FISKER'),
            array('type_id' => '4','make' => 'FORD'),
            array('type_id' => '4','make' => 'FORD DUTTON'),
            array('type_id' => '4','make' => 'FURORE'),
            array('type_id' => '4','make' => 'GBS'),
            array('type_id' => '4','make' => 'GMC'),
            array('type_id' => '4','make' => 'GARDENER'),
            array('type_id' => '4','make' => 'GILBERN'),
            array('type_id' => '4','make' => 'GINETTA'),
            array('type_id' => '4','make' => 'GOGGOMOBIL'),
            array('type_id' => '4','make' => 'GOINGREEN'),
            array('type_id' => '4','make' => 'GRIFFON'),
            array('type_id' => '4','make' => 'GRINNALL'),
            array('type_id' => '4','make' => 'GUMPERT'),
            array('type_id' => '4','make' => 'HENNESSEY'),
            array('type_id' => '4','make' => 'HERALD MOTOR CO'),
            array('type_id' => '4','make' => 'HILLMAN'),
            array('type_id' => '4','make' => 'HOLDEN'),
            array('type_id' => '4','make' => 'HONDA'),
            array('type_id' => '4','make' => 'HOTCHKISS'),
            array('type_id' => '4','make' => 'HUDSON'),
            array('type_id' => '4','make' => 'HUMBER'),
            array('type_id' => '4','make' => 'HUMMER'),
            array('type_id' => '4','make' => 'HYUNDAI'),
            array('type_id' => '4','make' => 'ISO'),
            array('type_id' => '4','make' => 'INFINITI'),
            array('type_id' => '4','make' => 'ISUZU'),
            array('type_id' => '4','make' => 'JBA'),
            array('type_id' => '4','make' => 'JAGUAR'),
            array('type_id' => '4','make' => 'JEEP'),
            array('type_id' => '4','make' => 'JENSEN'),
            array('type_id' => '4','make' => 'JOWETT'),
            array('type_id' => '4','make' => 'KTM'),
            array('type_id' => '4','make' => 'KHALEEJ'),
            array('type_id' => '4','make' => 'KIA'),
            array('type_id' => '4','make' => 'KOENIGSEGG'),
            array('type_id' => '4','make' => 'LEVC'),
            array('type_id' => '4','make' => 'LADA'),
            array('type_id' => '4','make' => 'LAMBORGHINI'),
            array('type_id' => '4','make' => 'LANCHESTER'),
            array('type_id' => '4','make' => 'LANCIA'),
            array('type_id' => '4','make' => 'LAND ROVER'),
            array('type_id' => '4','make' => 'LEA FRANCIS'),
            array('type_id' => '4','make' => 'LEXUS'),
            array('type_id' => '4','make' => 'LIGIER'),
            array('type_id' => '4','make' => 'LINCOLN'),
            array('type_id' => '4','make' => 'LISTER'),
            array('type_id' => '4','make' => 'LOBINI'),
            array('type_id' => '4','make' => 'LOCUST'),
            array('type_id' => '4','make' => 'LONDON TAXIS INTERNATIONAL'),
            array('type_id' => '4','make' => 'LONSDALE'),
            array('type_id' => '4','make' => 'LOTUS'),
            array('type_id' => '4','make' => 'MG'),
            array('type_id' => '4','make' => 'MINI'),
            array('type_id' => '4','make' => 'MK'),
            array('type_id' => '4','make' => 'MNR'),
            array('type_id' => '4','make' => 'MP LAFER'),
            array('type_id' => '4','make' => 'MACNEILLIE'),
            array('type_id' => '4','make' => 'MAHINDRA'),
            array('type_id' => '4','make' => 'MARCOS'),
            array('type_id' => '4','make' => 'MARLIN'),
            array('type_id' => '4','make' => 'MASERATI'),
            array('type_id' => '4','make' => 'MAYBACH'),
            array('type_id' => '4','make' => 'MAZDA'),
            array('type_id' => '4','make' => 'MCLAREN'),
            array('type_id' => '4','make' => 'MERCEDES-BENZ'),
            array('type_id' => '4','make' => 'MERCURY'),
            array('type_id' => '4','make' => 'MERLIN'),
            array('type_id' => '4','make' => 'MESSERSCHMITT'),
            array('type_id' => '4','make' => 'MEV'),
            array('type_id' => '4','make' => 'MIA'),
            array('type_id' => '4','make' => 'MICROCAR'),
            array('type_id' => '4','make' => 'MINARDI'),
            array('type_id' => '4','make' => 'MITSUBISHI'),
            array('type_id' => '4','make' => 'MITSUOKA'),
            array('type_id' => '4','make' => 'MORGAN'),
            array('type_id' => '4','make' => 'MORRIS'),
            array('type_id' => '4','make' => 'MOSLER'),
            array('type_id' => '4','make' => 'MYCAR'),
            array('type_id' => '4','make' => 'NG'),
            array('type_id' => '4','make' => 'NSU'),
            array('type_id' => '4','make' => 'NASH'),
            array('type_id' => '4','make' => 'NAYLOR'),
            array('type_id' => '4','make' => 'NISSAN'),
            array('type_id' => '4','make' => 'NOBLE'),
            array('type_id' => '4','make' => 'OKA'),
            array('type_id' => '4','make' => 'OLDSMOBILE'),
            array('type_id' => '4','make' => 'OPEL'),
            array('type_id' => '4','make' => 'PACKARD'),
            array('type_id' => '4','make' => 'PAGANI'),
            array('type_id' => '4','make' => 'PANHARD'),
            array('type_id' => '4','make' => 'PANTHER'),
            array('type_id' => '4','make' => 'PERODUA'),
            array('type_id' => '4','make' => 'PEUGEOT'),
            array('type_id' => '4','make' => 'PILGRIM'),
            array('type_id' => '4','make' => 'PLYMOUTH'),
            array('type_id' => '4','make' => 'PONTIAC'),
            array('type_id' => '4','make' => 'PORSCHE'),
            array('type_id' => '4','make' => 'PORTARO'),
            array('type_id' => '4','make' => 'PROTON'),
            array('type_id' => '4','make' => 'PROVA'),
            array('type_id' => '4','make' => 'QUANTUM'),
            array('type_id' => '4','make' => 'RCR'),
            array('type_id' => '4','make' => 'RADICAL'),
            array('type_id' => '4','make' => 'RAGE'),
            array('type_id' => '4','make' => 'RAW'),
            array('type_id' => '4','make' => 'RAYVOLUTION'),
            array('type_id' => '4','make' => 'RELIANT'),
            array('type_id' => '4','make' => 'RENAULT'),
            array('type_id' => '4','make' => 'REVA'),
            array('type_id' => '4','make' => 'REYNARD'),
            array('type_id' => '4','make' => 'RILEY'),
            array('type_id' => '4','make' => 'ROBIN HOOD'),
            array('type_id' => '4','make' => 'ROLLS-ROYCE'),
            array('type_id' => '4','make' => 'ROVER'),
            array('type_id' => '4','make' => 'ROYALE'),
            array('type_id' => '4','make' => 'SEAT'),
            array('type_id' => '4','make' => 'SSC'),
            array('type_id' => '4','make' => 'SAAB'),
            array('type_id' => '4','make' => 'SAN'),
            array('type_id' => '4','make' => 'SAO'),
            array('type_id' => '4','make' => 'SATURN'),
            array('type_id' => '4','make' => 'SEBRING'),
            array('type_id' => '4','make' => 'SECMA'),
            array('type_id' => '4','make' => 'SIMCA'),
            array('type_id' => '4','make' => 'SINGER'),
            array('type_id' => '4','make' => 'SKODA'),
            array('type_id' => '4','make' => 'SMART'),
            array('type_id' => '4','make' => 'SPECTRE'),
            array('type_id' => '4','make' => 'SPYKER'),
            array('type_id' => '4','make' => 'SSANGYONG'),
            array('type_id' => '4','make' => 'STANDARD'),
            array('type_id' => '4','make' => 'STAR'),
            array('type_id' => '4','make' => 'STARTINS'),
            array('type_id' => '4','make' => 'STUDEBAKER'),
            array('type_id' => '4','make' => 'SUBARU'),
            array('type_id' => '4','make' => 'SUNBEAM'),
            array('type_id' => '4','make' => 'SUZUKI'),
            array('type_id' => '4','make' => 'SWALLOW SIDECAR'),
            array('type_id' => '4','make' => 'SYLVA'),
            array('type_id' => '4','make' => 'TVR'),
            array('type_id' => '4','make' => 'TALBOT'),
            array('type_id' => '4','make' => 'TATA'),
            array('type_id' => '4','make' => 'TESLA'),
            array('type_id' => '4','make' => 'THRUXTON'),
            array('type_id' => '4','make' => 'TIGER'),
            array('type_id' => '4','make' => 'TONIQ'),
            array('type_id' => '4','make' => 'TOYOTA'),
            array('type_id' => '4','make' => 'TRABANT'),
            array('type_id' => '4','make' => 'TRIUMPH'),
            array('type_id' => '4','make' => 'TUK TUK'),
            array('type_id' => '4','make' => 'ULTIMA'),
            array('type_id' => '4','make' => 'VAUXHALL'),
            array('type_id' => '4','make' => 'VENTURI'),
            array('type_id' => '4','make' => 'VEXEL'),
            array('type_id' => '4','make' => 'VOLKSWAGEN'),
            array('type_id' => '4','make' => 'VOLVO'),
            array('type_id' => '4','make' => 'WEISMANN'),
            array('type_id' => '4','make' => 'WESTFIELD'),
            array('type_id' => '4','make' => 'WIESMANN'),
            array('type_id' => '4','make' => 'WILLYS KNIGHT'),
            array('type_id' => '4','make' => 'WOLSELEY'),
            array('type_id' => '4','make' => 'YAMAHA'),
            array('type_id' => '4','make' => 'YUGO'),
            array('type_id' => '4','make' => 'ZENOS'),
            array('type_id' => '5','make' => 'AIXAM'),
            array('type_id' => '5','make' => 'ALLIED'),
            array('type_id' => '5','make' => 'ASIA'),
            array('type_id' => '5','make' => 'AUVERLAND'),
            array('type_id' => '5','make' => 'AZURE DYNAMICS'),
            array('type_id' => '5','make' => 'BEDFORD'),
            array('type_id' => '5','make' => 'BREMACH'),
            array('type_id' => '5','make' => 'CHEVROLET'),
            array('type_id' => '5','make' => 'CITROEN'),
            array('type_id' => '5','make' => 'DAF'),
            array('type_id' => '5','make' => 'DFM'),
            array('type_id' => '5','make' => 'DFSK'),
            array('type_id' => '5','make' => 'DACIA'),
            array('type_id' => '5','make' => 'DAIHATSU'),
            array('type_id' => '5','make' => 'FSO'),
            array('type_id' => '5','make' => 'FIAT'),
            array('type_id' => '5','make' => 'FLEUR DE LYS'),
            array('type_id' => '5','make' => 'FORD'),
            array('type_id' => '5','make' => 'FREIGHT-ROVER'),
            array('type_id' => '5','make' => 'FREIGHTLINER'),
            array('type_id' => '5','make' => 'GOUPIL'),
            array('type_id' => '5','make' => 'HONDA'),
            array('type_id' => '5','make' => 'HYUNDAI'),
            array('type_id' => '5','make' => 'ISUZU'),
            array('type_id' => '5','make' => 'IVECO'),
            array('type_id' => '5','make' => 'JEEP'),
            array('type_id' => '5','make' => 'KIA'),
            array('type_id' => '5','make' => 'LDV'),
            array('type_id' => '5','make' => 'LADA'),
            array('type_id' => '5','make' => 'LAND ROVER'),
            array('type_id' => '5','make' => 'LEYLAND DAF'),
            array('type_id' => '5','make' => 'M.A.N.'),
            array('type_id' => '5','make' => 'MAN'),
            array('type_id' => '5','make' => 'MG'),
            array('type_id' => '5','make' => 'MINI'),
            array('type_id' => '5','make' => 'MAHINDRA'),
            array('type_id' => '5','make' => 'MAZDA'),
            array('type_id' => '5','make' => 'MEGA'),
            array('type_id' => '5','make' => 'MERCEDES-BENZ'),
            array('type_id' => '5','make' => 'METROCAB'),
            array('type_id' => '5','make' => 'MIA'),
            array('type_id' => '5','make' => 'MITSUBISHI'),
            array('type_id' => '5','make' => 'MORRIS'),
            array('type_id' => '5','make' => 'MORRISON'),
            array('type_id' => '5','make' => 'MULTICAR'),
            array('type_id' => '5','make' => 'NISSAN'),
            array('type_id' => '5','make' => 'PAMPAS'),
            array('type_id' => '5','make' => 'PEUGEOT'),
            array('type_id' => '5','make' => 'PIAGGIO'),
            array('type_id' => '5','make' => 'PROTON'),
            array('type_id' => '5','make' => 'RELIANT'),
            array('type_id' => '5','make' => 'RENAULT'),
            array('type_id' => '5','make' => 'ROVER'),
            array('type_id' => '5','make' => 'SAIC'),
            array('type_id' => '5','make' => 'SEAT'),
            array('type_id' => '5','make' => 'SANTANA'),
            array('type_id' => '5','make' => 'SKODA'),
            array('type_id' => '5','make' => 'SMITH'),
            array('type_id' => '5','make' => 'SSANGYONG'),
            array('type_id' => '5','make' => 'SUBARU'),
            array('type_id' => '5','make' => 'SUZUKI'),
            array('type_id' => '5','make' => 'TALBOT'),
            array('type_id' => '5','make' => 'TATA'),
            array('type_id' => '5','make' => 'TOYOTA'),
            array('type_id' => '5','make' => 'UMM'),
            array('type_id' => '5','make' => 'VT360'),
            array('type_id' => '5','make' => 'VAUXHALL'),
            array('type_id' => '5','make' => 'VOLKSWAGEN'),
            array('type_id' => '5','make' => 'WELLHOUSE'),
            array('type_id' => '5','make' => 'YUEJIN'),
            array('type_id' => '5','make' => 'YUGO'),
            array('type_id' => '5','make' => 'OTHER')
        );

        DB::table("makes")->insert($makes);
    }
}
