<?php

use Illuminate\Database\Seeder;

class SubCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("sub_categories")->insert([
            [ 'category_id' => 3, 'sub_category' => 'Drawbar Trailers'],
            [ 'category_id' => 3, 'sub_category' => 'Semi Trailers'],
            [ 'category_id' => 4, 'sub_category' => 'Articulated Platforms'],
            [ 'category_id' => 4, 'sub_category' => 'Attachments'],
            [ 'category_id' => 4, 'sub_category' => 'Scissors'],
            [ 'category_id' => 4, 'sub_category' => 'Telescopic Platforms'],
            [ 'category_id' => 5, 'sub_category' => 'Other'],
            [ 'category_id' => 6, 'sub_category' => 'Buildings'],
            [ 'category_id' => 6, 'sub_category' => 'Containers'],
            [ 'category_id' => 6, 'sub_category' => 'Farm Related'],
            [ 'category_id' => 6, 'sub_category' => 'Tanks'],
            [ 'category_id' => 6, 'sub_category' => 'Water and Fuel Bowers'],
            [ 'category_id' => 6, 'sub_category' => 'Welfare Units'],
            [ 'category_id' => 7, 'sub_category' => "Attachments"],
            [ 'category_id' => 7, 'sub_category' => "Combination"],
            [ 'category_id' => 7, 'sub_category' => "Double Drum"],
            [ 'category_id' => 7, 'sub_category' => "Plate Compactor"],
            [ 'category_id' => 7, 'sub_category' => "Pneumatic"],
            [ 'category_id' => 7, 'sub_category' => "Single Drum Padfoot"],
            [ 'category_id' => 7, 'sub_category' => "Single Drum Smooth"],
            [ 'category_id' => 7, 'sub_category' => "Trench"],
            [ 'category_id' => 8, 'sub_category' => "Static"],
            [ 'category_id' => 8, 'sub_category' => "Trailer"],
            [ 'category_id' => 9, 'sub_category' => "Batching and Silos"],
            [ 'category_id' => 9, 'sub_category' => "Mixer"],
            [ 'category_id' => 9, 'sub_category' => "Pumps"],
            [ 'category_id' => 10, 'sub_category' => "Conveyor Belts"],
            [ 'category_id' => 11, 'sub_category' => "All Terrain Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Attachments"],
            [ 'category_id' => 11, 'sub_category' => "Crawler Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Gantry Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Jib Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Overhead Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Rough Terrain Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Self Erecting Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Sidelift Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Tower Cranes"],
            [ 'category_id' => 11, 'sub_category' => "Truck Mounted Cranes"],
            [ 'category_id' => 12, 'sub_category' => "Attachments"],
            [ 'category_id' => 12, 'sub_category' => "Tracked Dozers"],
            [ 'category_id' => 12, 'sub_category' => "Wheeled Dozers"],
            [ 'category_id' => 13, 'sub_category' => "Articulated Dump Trucks"],
            [ 'category_id' => 13, 'sub_category' => "Attachments"],
            [ 'category_id' => 13, 'sub_category' => "Dump Trucks"],
            [ 'category_id' => 13, 'sub_category' => "Mini Dumpers"],
            [ 'category_id' => 13, 'sub_category' => "Skip Dumpers"],
            [ 'category_id' => 13, 'sub_category' => "Track Dumpers"],
            [ 'category_id' => 14, 'sub_category' => "Attachments"],
            [ 'category_id' => 14, 'sub_category' => "Micro Excavators"],
            [ 'category_id' => 14, 'sub_category' => "Midi Excavators"],
            [ 'category_id' => 14, 'sub_category' => "Mini Excavators"],
            [ 'category_id' => 14, 'sub_category' => "Track Excavators"],
            [ 'category_id' => 14, 'sub_category' => "Wheeled Excavators"],
            [ 'category_id' => 15, 'sub_category' => "All Terrain Forklifts"],
            [ 'category_id' => 15, 'sub_category' => "Attachments"],
            [ 'category_id' => 15, 'sub_category' => "Container Handlers"],
            [ 'category_id' => 15, 'sub_category' => "Counter Balanced Forklifts"],
            [ 'category_id' => 15, 'sub_category' => "Narrow Aisle Trucks"],
            [ 'category_id' => 15, 'sub_category' => "Pedestrian Stackers"],
            [ 'category_id' => 15, 'sub_category' => "Reach Trucks"],
            [ 'category_id' => 15, 'sub_category' => "Side Loaders"],
            [ 'category_id' => 16, 'sub_category' => "Static"],
            [ 'category_id' => 16, 'sub_category' => "Trailer"],
            [ 'category_id' => 17, 'sub_category' => "Graders"],
            [ 'category_id' => 18, 'sub_category' => "Attachments"],
            [ 'category_id' => 18, 'sub_category' => "Backhoe Loaders"],
            [ 'category_id' => 18, 'sub_category' => "Front Shovels"],
            [ 'category_id' => 18, 'sub_category' => "Multi Terrain Loaders"],
            [ 'category_id' => 18, 'sub_category' => "Skid Steer Loaders"],
            [ 'category_id' => 18, 'sub_category' => "Track Loaders"],
            [ 'category_id' => 18, 'sub_category' => "Wheeled Loaders"],
            [ 'category_id' => 19, 'sub_category' => "Mining and Quarry Equipment"],
            [ 'category_id' => 20, 'sub_category' => "Road Construction Equipment"],
            [ 'category_id' => 21, 'sub_category' => "Road and Paving Machine"],
            [ 'category_id' => 22, 'sub_category' => "Scrappers"],
            [ 'category_id' => 23, 'sub_category' => "Telehandlers"],
            [ 'category_id' => 24, 'sub_category' => "Access Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Attachments"],
            [ 'category_id' => 24, 'sub_category' => "Climate Control Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Gas Tools"],
            [ 'category_id' => 24, 'sub_category' => "Hand Tools"],
            [ 'category_id' => 24, 'sub_category' => "Lifting Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Lighting Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Plumbing Tools"],
            [ 'category_id' => 24, 'sub_category' => "Pneumatic Tools"],
            [ 'category_id' => 24, 'sub_category' => "Power Tools"],
            [ 'category_id' => 24, 'sub_category' => "Pumps and hydraulic Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Safety Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Scaffolding Equipment"],
            [ 'category_id' => 24, 'sub_category' => "Welding and Pipework Tools"],
            [ 'category_id' => 25, 'sub_category' => "Advertising and Exhibition"],
            [ 'category_id' => 25, 'sub_category' => "All Terrain"],
            [ 'category_id' => 25, 'sub_category' => "Attachments"],
            [ 'category_id' => 25, 'sub_category' => "Boat Transporter"],
            [ 'category_id' => 25, 'sub_category' => "Box"],
            [ 'category_id' => 25, 'sub_category' => "Car Transporter"],
            [ 'category_id' => 25, 'sub_category' => "Draw bar trailers"],
            [ 'category_id' => 25, 'sub_category' => "Farm Trailer"],
            [ 'category_id' => 25, 'sub_category' => "Flatbed"],
            [ 'category_id' => 25, 'sub_category' => "General Purpose"],
            [ 'category_id' => 25, 'sub_category' => "Hook Loader"],
            [ 'category_id' => 25, 'sub_category' => "Horse and Livestock"],
            [ 'category_id' => 25, 'sub_category' => "Skip Loader"],
            [ 'category_id' => 25, 'sub_category' => "Tipping"],
            [ 'category_id' => 26, 'sub_category' => "Attachments"],
            [ 'category_id' => 26, 'sub_category' => "Other Waste and Recycling"],
            [ 'category_id' => 26, 'sub_category' => "Skips"],
            [ 'category_id' => 26, 'sub_category' => "Sweepers"],
            [ 'category_id' => 26, 'sub_category' => "Waste Compactors"],
            [ 'category_id' => 26, 'sub_category' => "Waste Shredders"],
            [ 'category_id' => 26, 'sub_category' => "Wood Chippers"],
            [ 'category_id' => 27, 'sub_category' => "4WD Vehicles"],
            [ 'category_id' => 28, 'sub_category' => "ATV Trailers"],
            [ 'category_id' => 28, 'sub_category' => "ATVs"],
            [ 'category_id' => 28, 'sub_category' => "Snowmobiles"],
            [ 'category_id' => 29, 'sub_category' => "Other Attachments"],
            [ 'category_id' => 30, 'sub_category' => "Bale Wrappers"],
            [ 'category_id' => 30, 'sub_category' => "Forage Harvesters"],
            [ 'category_id' => 30, 'sub_category' => "Forage and Hay Attachments"],
            [ 'category_id' => 30, 'sub_category' => "Forage and Hay Other"],
            [ 'category_id' => 30, 'sub_category' => "Hay Bobs"],
            [ 'category_id' => 30, 'sub_category' => "Mower-conditioners"],
            [ 'category_id' => 30, 'sub_category' => "Mowers"],
            [ 'category_id' => 30, 'sub_category' => "Rakes"],
            [ 'category_id' => 30, 'sub_category' => "Round Balers"],
            [ 'category_id' => 30, 'sub_category' => "Square Balers"],
            [ 'category_id' => 30, 'sub_category' => "Stacking and loading Equipment"],
            [ 'category_id' => 30, 'sub_category' => "Toppers"],
            [ 'category_id' => 30, 'sub_category' => "Windrowers"],
            [ 'category_id' => 31, 'sub_category' => "Bundlers"],
            [ 'category_id' => 31, 'sub_category' => "Feller Bunchers"],
            [ 'category_id' => 31, 'sub_category' => "Forestry Mowers"],
            [ 'category_id' => 31, 'sub_category' => "Forestry and Hedging Attachments"],
            [ 'category_id' => 31, 'sub_category' => "Forestry and Hedging Other"],
            [ 'category_id' => 31, 'sub_category' => "Forwarders"],
            [ 'category_id' => 31, 'sub_category' => "Hedge Mowers"],
            [ 'category_id' => 31, 'sub_category' => "Loaders"],
            [ 'category_id' => 31, 'sub_category' => "Skidders"],
            [ 'category_id' => 31, 'sub_category' => "Stump Grinders"],
            [ 'category_id' => 31, 'sub_category' => "Tree Harvesters"],
            [ 'category_id' => 31, 'sub_category' => "Verge Mowers"],
            [ 'category_id' => 31, 'sub_category' => "Wood Chippers"],
            [ 'category_id' => 32, 'sub_category' => "Ground Care Other"],
            [ 'category_id' => 32, 'sub_category' => "Ride on Mowers"],
            [ 'category_id' => 33, 'sub_category' => "Beet Harvesters"],
            [ 'category_id' => 33, 'sub_category' => "Chaser Bins"],
            [ 'category_id' => 33, 'sub_category' => "Combine Harvesters"],
            [ 'category_id' => 33, 'sub_category' => "Forage Harvesters"],
            [ 'category_id' => 33, 'sub_category' => "Fruit Harvesters"],
            [ 'category_id' => 33, 'sub_category' => "Harvester Attachments"],
            [ 'category_id' => 33, 'sub_category' => "Other Harvesters"],
            [ 'category_id' => 33, 'sub_category' => "Potato Harvesters"],
            [ 'category_id' => 34, 'sub_category' => "Bale Shredders and Spreaders"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Equipment Attachments"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Equipment Other"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Tow Ball Trailers"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Truck Box Body"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Truck Drawbar Trailers"],
            [ 'category_id' => 34, 'sub_category' => "Livestock Trucks"],
            [ 'category_id' => 35, 'sub_category' => "Attachments"],
            [ 'category_id' => 35, 'sub_category' => "Plant Excavators"],
            [ 'category_id' => 35, 'sub_category' => "Plant Loaders"],
            [ 'category_id' => 35, 'sub_category' => "Telehandlers"],
            [ 'category_id' => 35, 'sub_category' => "Tractor Based Excavators"],
            [ 'category_id' => 35, 'sub_category' => "Tractor Based Loaders"],
            [ 'category_id' => 36, 'sub_category' => "Broadcast Spreaders"],
            [ 'category_id' => 36, 'sub_category' => "Combination Drills"],
            [ 'category_id' => 36, 'sub_category' => "Planters"],
            [ 'category_id' => 36, 'sub_category' => "Precision Seeders"],
            [ 'category_id' => 36, 'sub_category' => "Seed Drills"],
            [ 'category_id' => 36, 'sub_category' => "Sowing and Planting Attachments"],
            [ 'category_id' => 36, 'sub_category' => "Sowing and Planting Other"],
            [ 'category_id' => 36, 'sub_category' => "Transplanters"],
            [ 'category_id' => 37, 'sub_category' => "Fertiliser Spreaders"],
            [ 'category_id' => 37, 'sub_category' => "Manure Spreaders"],
            [ 'category_id' => 37, 'sub_category' => "Other Sprayers and Spreaders"],
            [ 'category_id' => 37, 'sub_category' => "Self Propelled Sprayers"],
            [ 'category_id' => 37, 'sub_category' => "Slurry Tankers"],
            [ 'category_id' => 37, 'sub_category' => "Spreaders and Sprayers Attachments"],
            [ 'category_id' => 37, 'sub_category' => "Tractor Mounted Sprayers"],
            [ 'category_id' => 37, 'sub_category' => "Trailer Sprayers"],
            [ 'category_id' => 38, 'sub_category' => "Conveyors"],
            [ 'category_id' => 38, 'sub_category' => "Gates and Fencing"],
            [ 'category_id' => 38, 'sub_category' => "Out Buildings"],
            [ 'category_id' => 38, 'sub_category' => "Silos"],
            [ 'category_id' => 38, 'sub_category' => "Storage and Buildings Other"],
            [ 'category_id' => 38, 'sub_category' => "Tanks"],
            [ 'category_id' => 39, 'sub_category' => "Aerators"],
            [ 'category_id' => 39, 'sub_category' => "Cultivators"],
            [ 'category_id' => 39, 'sub_category' => "Harrows"],
            [ 'category_id' => 39, 'sub_category' => "Ploughs"],
            [ 'category_id' => 39, 'sub_category' => "Power Harrows"],
            [ 'category_id' => 39, 'sub_category' => "Rollers"],
            [ 'category_id' => 39, 'sub_category' => "Stone Removal and Crushers"],
            [ 'category_id' => 39, 'sub_category' => "Subsoilers"],
            [ 'category_id' => 39, 'sub_category' => "Tillage Attachments"],
            [ 'category_id' => 39, 'sub_category' => "Tillage Other"],
            [ 'category_id' => 40, 'sub_category' => "Compact Tractor"],
            [ 'category_id' => 40, 'sub_category' => "Large Tractor"],
            [ 'category_id' => 40, 'sub_category' => "Medium Tractor"],
            [ 'category_id' => 40, 'sub_category' => "Other Tractors"],
            [ 'category_id' => 40, 'sub_category' => "Small Tractor"],
            [ 'category_id' => 40, 'sub_category' => "Tractor Attachments"],
            [ 'category_id' => 41, 'sub_category' => "ATV Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Bale Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Car and Van Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Chaser Bins"],
            [ 'category_id' => 41, 'sub_category' => "Dropside Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Dumper Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Farm Trailer Attachments"],
            [ 'category_id' => 41, 'sub_category' => "Flatbed Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Grain and Silage Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Livestock Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Other Trailers"],
            [ 'category_id' => 41, 'sub_category' => "Truck Trailers"]
            
        ]);
    }
}
